---
- name: Create Directories
  loop: "{{ namespaces }}"
  file:
    path: /tmp/{{ cluster_fqdn }}/{{ item.name }}
    state: directory

- name: Template Files
  loop: "{{ namespaces }}"
  template:
    src: ns.j2
    dest: /tmp/{{ cluster_fqdn }}/{{ item.name }}/ns.yaml

- name: Apply Resources
  when: ('dry-run' not in ansible_run_tags)
  loop: "{{ namespaces }}"
  community.kubernetes.k8s:
    state: present
    src: /tmp/{{ cluster_fqdn }}/{{ item.name }}/ns.yaml

- name: Template flux-kustomization
  loop: "{{ namespaces }}"
  template:
    src: flux-kustomization.j2
    dest: /tmp/{{ cluster_fqdn }}/platform/flux-system/watches/{{ item.name }}.yaml
