---
- name: Create Directory
  file:
    path: /tmp/{{ cluster_fqdn }}/platform/postgresql/default
    state: directory

- include_tasks: generate-variables.yaml

- name: Template Files
  template:
    src: "{{ item.name }}.j2"
    dest: /tmp/{{ cluster_fqdn }}/platform/postgresql/{{ item.dest | default(item.name) }}.yaml
  when: item.condition | default(true)
  loop:
    - name: secret-pg-creds
      dest: default/secret-pg-creds
    - name: secret-schema-init-script
      dest: default/secret-schema-init-script

- name: Copy Files
  copy:
    src: "{{ item.name }}"
    dest: /tmp/{{ cluster_fqdn }}/platform/postgresql/{{ item.dest | default(item.name) }}
  when: item.condition | default(true)
  loop:
    - name: kustomization.yaml
    - name: ns.yaml
    - name: job-schema-init.yaml
      dest: default/job-schema-init.yaml
    - name: release.yaml
      dest: default/release.yaml

- name: Seal Secrets
  tags: [ requires_cluster]
  when: item.condition | default(true)
  shell: |
    kubeseal --format=yaml </tmp/{{ cluster_fqdn }}/platform/postgresql/{{ item.name }}.yaml >/tmp/{{ cluster_fqdn }}/platform/postgresql/{{ item.name }}.tmp
    mv /tmp/{{ cluster_fqdn }}/platform/postgresql/{{ item.name }}.tmp /tmp/{{ cluster_fqdn }}/platform/postgresql/{{ item.name }}.yaml
  loop:
    - name: default/secret-pg-creds
    - name: default/secret-schema-init-script

- name: Apply Resources
  tags: [ requires_cluster]
  loop: "{{ lookup('ms3_inc.tavros.kustomize', '/tmp/' + cluster_fqdn + '/platform/postgresql/', reorder='none') }}"
  community.kubernetes.k8s:
    definition: "{{ item }}"
    wait: true
    wait_condition: "{{ wait_conditions[item.kind] | default(omit) }}"
    wait_timeout: 900

- name: Template flux-kustomization
  template:
    src: flux-kustomization.j2
    dest: /tmp/{{ cluster_fqdn }}/platform/flux-system/watches/postgresql.yaml
