---
- name: Create directory
  file:
    path: /tmp/{{ cluster_domain }}/platform/postgresql/
    state: directory

- name: Set postgresql password
  set_fact:
    postgresql_password: lookup('password', '/dev/null length=12 chars=ascii_letters') | string

- name: Set postgresql postgres password
  set_fact:
    postgresql_postgres_password: lookup('password', '/dev/null length=12 chars=ascii_letters') | string

- name: Process config-secret template
  template:
    src: config-secret.j2
    dest: /tmp/{{ cluster_domain }}/platform/postgresql/config-secret.yaml

- name: Convert config-secret to SealedSecret
  when: "'dry-run' not in ansible_run_tags"
  shell: |
    kubeseal --format=yaml </tmp/{{ cluster_domain }}/platform/postgresql/config-secret.yaml >/tmp/{{ cluster_domain }}/platform/postgresql/config-secret.tmp
    mv /tmp/{{ cluster_domain }}/platform/postgresql/config-secret.tmp /tmp/{{ cluster_domain }}/platform/postgresql/config-secret.yaml

- name: Copy setup.sql
  copy:
    src: setup.sql
    dest: /tmp/{{ cluster_domain }}/platform/postgresql/setup.sql

- name: Copy postgresql namespace
  copy:
    src: ns.yaml
    dest: /tmp/{{ cluster_domain }}/platform/postgresql/ns.yaml

- name: Copy postgresql default release
  copy:
    src: default-release.yaml
    dest: /tmp/{{ cluster_domain }}/platform/postgresql/default-release.yaml

- name: Copy postgresql kustomization
  copy:
    src: kustomization.yaml
    dest: /tmp/{{ cluster_domain }}/platform/postgresql/kustomization.yaml

- name: Apply manifests
  when: "'dry-run' not in ansible_run_tags"
  with_ms3_inc.troubadour.kustomize: /tmp/{{ cluster_domain }}/platform/postgresql/
  k8s:
    definition: "{{ item }}"
    wait: true
    wait_condition: "{{ wait_conditions[item.kind] }}"

- name: Process flux-kustomization template
  template:
    src: flux-kustomization.j2
    dest: /tmp/{{ cluster_domain }}/platform/flux-system/watches/postgresql.yaml
