---
- name: Create directory
  file:
    path: ./{{ cluster_domain }}/platform/kuma-system/meshes/
    state: directory

- name: Process mesh template
  with_list: '{{ meshes }}'
  template:
    src: mesh.j2
    dest: ./{{ cluster_domain }}/platform/kuma-system/meshes/{{ item.mesh_name }}.yaml

- name: Process kuma kustomization template
  template:
    src: kustomization.j2
    dest: ./{{ cluster_domain }}/platform/kuma-system/kustomization.yaml

- name: Apply Kuma release
  shell: |
    kustomize build ./troubadour-base/kuma/ | kubectl apply -f -

- name: Wait for Kuma HelmRelease, and Deployment
  shell: |
    kubectl -n kuma-system wait --for=condition=ready --timeout=120s helmrelease.helm.toolkit.fluxcd.io --all
    kubectl -n kuma-system wait --for=condition=available --timeout=120s deployments --all

- name: Apply Kuma Mehses
  shell: |
    kustomize build ./{{ cluster_domain }}/platform/kuma-system/ | kubectl apply -f -

- name: Process flux-kustomization template
  template:
    src: flux-kustomization.j2
    dest: ./{{ cluster_domain }}/platform/flux-system/watches/kuma-system.yaml

# Todo Resolve Restart Issue on Kuma Pod
- name: Wait for Kuma Pod
  shell: |
    kubectl -n kuma-system wait --for=condition=ready --timeout=120s pods --all