apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

resources:
- crds/keycloak.org_keycloakbackups_crd.yaml
- crds/keycloak.org_keycloakclients_crd.yaml
- crds/keycloak.org_keycloakrealms_crd.yaml
- crds/keycloak.org_keycloaks_crd.yaml
- crds/keycloak.org_keycloakusers_crd.yaml
- namespace.yaml
- role.yaml
- role_binding.yaml
- service_account.yaml
- operator.yaml
