apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: keycloak
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./troubadour.ms3-inc.com/platform/keycloak
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  prune: true
  timeout: 5m0s