- name: Create directory
  file:
    path: ./{{ cluster_domain }}/platform/flux-system/watches
    state: directory

- name: Generate Flux manifests
  shell: |
    flux install --version=latest \
      --arch=amd64 \
      --export > ./{{ cluster_domain }}/platform/flux-system/gotk-components.yaml

- name: Process gotk-sync template
  template:
    src: gotk-sync.j2
    dest: ./{{ cluster_domain }}/platform/flux-system/gotk-sync.yaml

- name: Apply Flux manifests
  when: "'dry-run' not in ansible_run_tags"
  shell: |
    kubectl apply -f ./{{ cluster_domain }}/platform/flux-system/gotk-components.yaml

- name: Wait for Flux Deployment
  when: "'dry-run' not in ansible_run_tags"
  shell: |
    kubectl -n flux-system wait --for=condition=available --timeout=120s deployments --all

# todo: add single source in each role instead of all at once
- name: Copy sources
  copy:
    src: sources.yaml
    dest: ./{{ cluster_domain }}/platform/flux-system/sources.yaml

- name: Apply Flux Source manifests
  when: "'dry-run' not in ansible_run_tags"
  shell: |
    kubectl create -f ./{{ cluster_domain }}/platform/flux-system/sources.yaml
