apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: troubadour
  namespace: jaeger
spec:
  strategy: production
  agent:
    strategy: DaemonSet
  ingress:
    enabled: false
    security: none
  collector:
    maxReplicas: 2
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
  ui:
    options:
      dependencies:
        menuEnabled: true
  storage:
    type: elasticsearch
    dependencies:
      enabled: true
      image: quay.io/jam01/jaeger-spark-dependencies:0.0.1-SNAPSHOT-001
      resources:
        requests:
          memory: 2048Mi
        limits:
          memory: 2048Mi
      javaOpts: -Djavax.net.ssl.trustStore=/es-tls/truststore.jks -Djavax.net.ssl.trustStorePassword=password
    options:
      es:
        server-urls: https://elasticsearch-es-http.elastic-system.svc:9200
        index-prefix: troubadour
        tls:
          ca: /es/certificates/ca.crt
    secretName: jaeger-es-secret
  volumeMounts:
    - name: certificates
      mountPath: /es/certificates/
      readOnly: true
  volumes:
    - name: certificates
      secret:
        secretName: es-http-certs
