---
- name: Create directory
  file:
    path: ./{{ cluster_domain }}/platform/kubeseal
    state: directory

- name: Copy kubeseal kustomization
  copy:
    src: kustomization.yaml
    dest: ./{{ cluster_domain }}/platform/kubeseal/kustomization.yaml

- name: Apply kubeseal manifests
  shell: |
    kustomize build ./{{ cluster_domain }}/platform/kubeseal/ | kubectl apply -f -

- name: Wait for Kubeseal Deployment
  shell: |
    kubectl -n kube-system wait --for=condition=available --timeout=120s deployment.apps/sealed-secrets-controller

- name: Process flux-kustomization template
  template:
    src: flux-kustomization.j2
    dest: ./{{ cluster_domain }}/platform/flux-system/watches/kubeseal.yaml