---
- name: Create Directory
  loop: "{{ keycloak.realms }}"
  file:
    path: /tmp/{{ cluster_fqdn }}/platform/keycloak/default/{{ item.name }}
    state: directory

- name: Generate keycloak.realms.admin_password Variables
  loop: "{{ keycloak.realms }}"
  set_fact:
    gen_keycloak_realms: "{{ (gen_keycloak_realms | default([])) + [ {'admin_password': lookup('password', '/dev/null')} | combine(item, recursive=true) ] }}"

- name: Merge keycloak.realms.admin_password Variables
  set_fact:
    keycloak: "{{ keycloak | combine({'realms': gen_keycloak_realms}, recursive=true) }}"

- name: Copy Files
  copy:
    src: "{{ item.name }}"
    dest: /tmp/{{ cluster_fqdn }}/platform/keycloak/{{ item.dest | default(item.name) }}
  when: item.condition | default(true)
  loop:
    - name: base-kustomization.yaml
      dest: kustomization.yaml
    - name: operator
      dest: ""

- name: Template Default Files
  template:
    src: "{{ item.name }}.j2"
    dest: /tmp/{{ cluster_fqdn }}/platform/keycloak/default/{{ item.dest | default(item.name) }}.yaml
  when: item.condition | default(true)
  loop:
    - name: secret-keycloak-db
    - name: ingress
    - name: instance-kustomization
      dest: kustomization

- name: Copy Default Files
  copy:
    src: "{{ item.name }}"
    dest: /tmp/{{ cluster_fqdn }}/platform/keycloak/default/{{ item.dest | default(item.name) }}
  when: item.condition | default(true)
  loop:
    - name: keycloak.yaml

- name: Template Realm Files
  template:
    src: "{{ item[1] }}.j2"
    dest: /tmp/{{ cluster_fqdn }}/platform/keycloak/default/{{ item[0].name }}/{{ item[1] }}.yaml
  with_nested:
    - "{{ keycloak.realms }}"
    - [ 'keycloakrealm', 'keycloakuser-admin' ]

- name: Seal Secrets
  when: ('dry-run' not in ansible_run_tags) and (item.condition | default(true))
  shell: |
    kubeseal --format=yaml </tmp/{{ cluster_fqdn }}/platform/keycloak/{{ item.name }}.yaml >/tmp/{{ cluster_fqdn }}/platform/keycloak/{{ item.name }}.tmp
    mv /tmp/{{ cluster_fqdn }}/platform/keycloak/{{ item.name }}.tmp /tmp/{{ cluster_fqdn }}/platform/keycloak/{{ item.name }}.yaml
  loop:
    - name: default/secret-keycloak-db

- name: Apply Operator Resources
  when: ('dry-run' not in ansible_run_tags)
  with_ms3_inc.tavros.kustomize:  /tmp/{{ cluster_fqdn }}/platform/keycloak/operator/12.0.1
  k8s:
    definition: "{{ item }}"
    wait: true
    wait_condition: "{{ wait_conditions[item.kind] | default(omit) }}"
    wait_timeout: 900

- name: Wait for Keycloak Operator
  when: ('dry-run' not in ansible_run_tags)
  community.kubernetes.k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: keycloak-operator
    namespace: keycloak
  register: keycloak_def
  until: ('status' in keycloak_def.resources[0]) and (keycloak_def.resources[0].status.readyReplicas >= 1)
  retries: 30
  delay: 30
  changed_when: false

- name: Apply Resources
  when: ('dry-run' not in ansible_run_tags)
  with_ms3_inc.tavros.kustomize:  /tmp/{{ cluster_fqdn }}/platform/keycloak/
  k8s:
    definition: "{{ item }}"
    wait: true
    wait_condition: "{{ wait_conditions[item.kind] | default(omit) }}"
    wait_timeout: 900

- name: Wait for Keycloak
  when: ('dry-run' not in ansible_run_tags)
  community.kubernetes.k8s_info:
    api_version: keycloak.org/v1alpha1
    kind: Keycloak
    name: tavros
    namespace: keycloak
  register: keycloak_def
  # https://github.com/keycloak/keycloak-operator/blob/11.0.3/deploy/crds/keycloak.org_keycloaks_crd.yaml#L175
  until: ('status' in keycloak_def.resources[0]) and (keycloak_def.resources[0].status.ready)
  retries: 30
  delay: 30
  changed_when: false

- name: Template flux-kustomization
  template:
    src: flux-kustomization.j2
    dest: /tmp/{{ cluster_fqdn }}/platform/flux-system/watches/keycloak.yaml
