---
- name: Create directory
  file:
    path: /tmp/{{ cluster_domain }}/platform/keycloak/default
    state: directory

- name: Copy operator
  copy:
    src: operator
    dest: /tmp/{{ cluster_domain }}/platform/keycloak/

- name: Apply operator manifests
  when: "'dry-run' not in ansible_run_tags"
  with_ms3_inc.troubadour.kustomize:  /tmp/{{ cluster_domain }}/platform/keycloak/operator/11.0.3/
  k8s:
    definition: "{{ item }}"
    wait: true

- name: Process keycloak-db-secret template
  template:
    src: keycloak-db-secret.j2
    dest: /tmp/{{ cluster_domain }}/platform/keycloak/default/keycloak-db-secret.yaml

- name: Convert keycloak-db-secret to SealedSecret
  when: "'dry-run' not in ansible_run_tags"
  shell: |
    kubeseal --format=yaml </tmp/{{ cluster_domain }}/platform/keycloak/default/keycloak-db-secret.yaml >/tmp/{{ cluster_domain }}/platform/keycloak/default/keycloak-db-secret.tmp
    mv /tmp/{{ cluster_domain }}/platform/keycloak/default/keycloak-db-secret.tmp /tmp/{{ cluster_domain }}/platform/keycloak/default/keycloak-db-secret.yaml

- name: Process ingress template
  template:
    src: ingress.j2
    dest: /tmp/{{ cluster_domain }}/platform/keycloak/default/ingress.yaml

- name: Copy default keycloak release
  copy:
    src: release.yaml
    dest: /tmp/{{ cluster_domain }}/platform/keycloak/default/release.yaml

- name: Copy default keycloak kustomization
  copy:
    src: instance-kustomization.yaml
    dest: /tmp/{{ cluster_domain }}/platform/keycloak/default/kustomization.yaml

- name: Copy base keycloak kustomization
  copy:
    src: base-kustomization.yaml
    dest: /tmp/{{ cluster_domain }}/platform/keycloak/kustomization.yaml

- name: Copy keycloak ns
  copy:
    src: ns.yaml
    dest: /tmp/{{ cluster_domain }}/platform/keycloak/ns.yaml

- name: Apply keycloak manifests
  when: "'dry-run' not in ansible_run_tags"
  with_ms3_inc.troubadour.kustomize:  /tmp/{{ cluster_domain }}/platform/keycloak/
  k8s:
    definition: "{{ item }}"
    wait: true
    wait_condition: "{{ wait_conditions[item.kind] }}"

- name: Wait for Keycloak
  when: "'dry-run' not in ansible_run_tags"
  community.kubernetes.k8s_info:
    kind: Keycloak
    name: troubadour-keycloak
    namespace: keycloak
  register: keycloak_def
  # https://github.com/keycloak/keycloak-operator/blob/11.0.3/deploy/crds/keycloak.org_keycloaks_crd.yaml#L175
  until: keycloak_def[0].status.ready
  changed_when: false

- name: Process flux-kustomization template
  template:
    src: flux-kustomization.j2
    dest: /tmp/{{ cluster_domain }}/platform/flux-system/watches/keycloak.yaml
