namespace: ms3_inc
name: tavros
version: 0.6.0
readme: README.md
authors:
  - Randy McCright <rmccright@ms3-inc.com>
  - Jose Montoya <jmontoya@ms3-inc.com>
description: A collection to provision MS3's Tavros Platform
dependencies:
  amazon.aws: ">=8.0.0,<10.0.0"
  community.aws: ">=8.0.0,<10.0.0"
  kubernetes.core: ">=5.0.0,<6.0.0"
  community.general: ">=9.0.0,<11.0.0"
  azure.azcollection: ">=2.7.0,<4.0.0"
  community.crypto: ">=2.0.0"
repository: https://github.com/MS3Inc/tavros
documentation: https://github.com/MS3Inc/tavros
homepage: https://github.com/MS3Inc/tavros
issues: https://github.com/MS3Inc/tavros/issues
