namespace: ms3_inc
name: tavros
version: 0.6.0
readme: README.md
authors:
- Randy McCright <rmccright@ms3-inc.com>
- Jose Montoya <jmontoya@ms3-inc.com>
description: A collection to provision MS3's Tavros Platform
dependencies:
  amazon.aws: '==1.4.0'
  community.aws: '==1.4.0'
  community.kubernetes: '==1.2.0'
  community.general: '==2.5.1'
repository: https://github.com/MS3Inc/tavros
documentation: https://github.com/MS3Inc/tavros
homepage: https://github.com/MS3Inc/tavros
issues: https://github.com/MS3Inc/tavros/issues
