apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: heartbeat
rules:
- apiGroups: [""]
  resources:
  - nodes
  - namespaces
  - events
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources:
  - replicasets
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
  - statefulsets
  - deployments
  verbs: ["get", "list", "watch"]
- apiGroups:
  - ""
  resources:
  - nodes/stats
  verbs:
  - get
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: heartbeat-svc
  namespace: elastic-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: heartbeat
subjects:
- kind: ServiceAccount
  name: heartbeat-svc
  namespace: elastic-system
roleRef:
  kind: ClusterRole
  name: heartbeat
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: tavros-heartbeat-prod
  namespace: elastic-system
spec:
  type: heartbeat
  version: 7.13.4
  elasticsearchRef:
    name: tavros
  config:
    heartbeat:
      autodiscover:
        providers:
        - type: kubernetes
          node: ${NODE_NAME}
          namespace: "prod"
          hints.enabled: true
  daemonSet:
    podTemplate:
      metadata:
        labels:
          kuma.io/sidecar-injection: enabled
        annotations:
          kuma.io/mesh: prod
      spec:
        serviceAccountName: heartbeat-svc
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
        containers:
        - name: heartbeat
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
---
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: tavros-heartbeat-dev
  namespace: elastic-system
spec:
  type: heartbeat
  version: 7.13.4
  elasticsearchRef:
    name: tavros
  config:
    heartbeat:
      autodiscover:
        providers:
        - type: kubernetes
          node: ${NODE_NAME}
          namespace: "dev"
          hints.enabled: true
  daemonSet:
    podTemplate:
      metadata:
        labels:
          kuma.io/sidecar-injection: enabled
        annotations:
          kuma.io/mesh: sandbox
      spec:
        serviceAccountName: heartbeat-svc
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
        containers:
        - name: heartbeat
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
---
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: tavros-heartbeat-test
  namespace: elastic-system
spec:
  type: heartbeat
  version: 7.13.4
  elasticsearchRef:
    name: tavros
  config:
    heartbeat:
      autodiscover:
        providers:
        - type: kubernetes
          node: ${NODE_NAME}
          namespace: "test"
          hints.enabled: true
  daemonSet:
    podTemplate:
      metadata:
        labels:
          kuma.io/sidecar-injection: enabled
        annotations:
          kuma.io/mesh: sandbox
      spec:
        serviceAccountName: heartbeat-svc
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
        containers:
        - name: heartbeat
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName