---
- name: Delete Cluster
  register: result
  changed_when: result.rc == 101
  failed_when: result.rc not in [100, 101]
  shell: |
    kops get cluster \
      --name {{ cluster_fqdn }} \
      --state s3://{{ kops.state_bucket }}
    if [[ $? -eq 1 ]]; then { exit 100; } fi

    kops delete cluster \
      --name="{{ cluster_fqdn }}" \
      --state="s3://{{ kops.state_bucket }}" \
      --yes
    if [ $? -eq 0 ]; then { exit 101; } fi

    echo "Failed to delete cluster"
    exit 1

- name: Get SP Access Keys
  shell: |
    aws iam list-access-keys --user-name {{ kops.state_bucket }}-sp
  register: result
    
- name: Delete SP Access Key
  shell: |
    aws iam delete-access-key --user-name {{ kops.state_bucket }}-sp --access-key-id {{ item.AccessKeyId }}
  loop: "{{ (result.stdout | from_json).AccessKeyMetadata }}"
  register: result

- name: Delete SP Policy
  shell: |
    aws iam delete-user-policy \
      --user-name {{ kops.state_bucket }}-sp \
      --policy-name {{ kops.state_bucket }}-sp
  register: result

- name: Delete AWS SP User
  shell: |
    aws iam delete-user --user-name {{ kops.state_bucket }}-sp
  register: result
