---
- name: Set kubernetes_cluster Default Variables
  set_fact:
    kubernetes_cluster: "{{ defaults | combine(kubernetes_cluster, recursive=true)  }}"
  vars:
    defaults:
      dns_zone: "{{ cluster_fqdn }}"

- name: Set kops Default Variables
  set_fact:
    kops: "{{ defaults | combine(kops, recursive=true)  }}"
  vars:
    defaults:
      state_bucket: "{{ cluster_fqdn }}-tavros"
      state_bucket_region: us-east-1

- include_tasks: create_cluster.yaml
  tags: [ requires_cluster ]
  when: ('dry-run' not in ansible_run_tags) and (cluster_state == 'present')

- include_tasks: delete_cluster.yaml
  tags: [ requires_cluster ]
  when: ('dry-run' not in ansible_run_tags) and (cluster_state == 'absent')
