apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: troubadour
spec:
  values:
    volumePermissions:
      securityContext:
        runAsUser: auto
    securityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
    shmVolume:
      chmod:
        enabled: false
