---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-repo-secret
  url: 'http://gitea-http.gitea.svc.cluster.local:3000/flux/troubadour'
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./troubadour.ms3-inc.com/platform/flux-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
