- name: Create Directory
  file:
    path: /tmp/{{ cluster_fqdn }}/platform/flux-system/watches
    state: directory

- name: Generate Flux GitOps Toolkit Resources
  shell: |
    flux install --version=v0.10.0 \
      --export > /tmp/{{ cluster_fqdn }}/platform/flux-system/gotk-components.yaml

- name: Template Files
  template:
    src: "{{ item.name }}.j2"
    dest: /tmp/{{ cluster_fqdn }}/platform/flux-system/{{ item.name }}.yaml
  when: item.condition | default(true)
  loop:
    - name: alert-slack
      condition: "{{ flux.alerts.slack.address is defined }}"

- name: Copy Files
  copy:
    src: "{{ item.name }}"
    dest: /tmp/{{ cluster_fqdn }}/platform/flux-system/{{ item.name }}
  when: item.condition | default(true)
  loop:
    # todo: add single source in each role instead of all at once
    - name: helmrepos.yaml

- name: Apply Resources
  tags: [ requires_cluster ]
  when: ('dry-run' not in ansible_run_tags)
  # difference(...) is added here because flux generates an extraneous yaml document marker at the end
  # see: https://curtisshoward.com/post/multi-document-yaml-files-and-the-ansible-k8s-module/
  loop: "{{ lookup('file', '/tmp/' + cluster_fqdn + '/platform/flux-system/gotk-components.yaml') | from_yaml_all | list | difference([None]) }}"
  loop_control:
    label: "{{ item.kind }}/{{ item.metadata.name | default('unnamed')}}"
  ms3_inc.tavros.kube:
    kubeconfig: '~/.kube/config'
    definition: "{{ item }}"
    wait: true
    wait_timeout: 900

- name: Apply HelmRepo Resources
  tags: [ requires_cluster ]
  when: ('dry-run' not in ansible_run_tags)
  loop: "{{ lookup('file', '/tmp/' + cluster_fqdn + '/platform/flux-system/helmrepos.yaml') | from_yaml_all | list | difference([None]) }}"
  loop_control:
    label: "{{ item.kind }}/{{ item.metadata.name | default('unnamed')}}"
  ms3_inc.tavros.kube:
    kubeconfig: '~/.kube/config'
    definition: "{{ item }}"
    wait: true
    wait_timeout: 900

- name: Apply Slack Alert Resource
  tags: [ requires_cluster ]
  when: ('dry-run' not in ansible_run_tags) and (flux.alerts.slack.address is defined)
  ms3_inc.tavros.kube:
    kubeconfig: '~/.kube/config'
    state: present
    src: /tmp/{{ cluster_fqdn }}/platform/flux-system/slack-alert.yaml
