---
- name: Delete Tavros Wildcard
  tags: [ requires_cluster ]
  when: ('dry-run' not in ansible_run_tags)
  script: "{{ role_path }}/files/delete-route53-record.sh '{{ kubernetes_cluster.dns_zone }}' '*.{{ cluster_fqdn }}'"

- name: Delete Tavros Sandbox Wildcard
  tags: [ requires_cluster ]
  when: ('dry-run' not in ansible_run_tags)
  script: "{{ role_path }}/files/delete-route53-record.sh '{{ kubernetes_cluster.dns_zone }}' '*.sandbox.{{ cluster_fqdn }}'"

- name: Delete Kong DNS
  tags: [ requires_cluster ]
  when: ('dry-run' not in ansible_run_tags)
  script: "{{ role_path }}/files/delete-route53-record.sh '{{ kubernetes_cluster.dns_zone }}' '*.prod-kong.{{ cluster_fqdn }}'"

- name: Delete Kong Sandbox DNS
  tags: [ requires_cluster ]
  when: ('dry-run' not in ansible_run_tags)
  script: "{{ role_path }}/files/delete-route53-record.sh '{{ kubernetes_cluster.dns_zone }}' '*.sandbox-kong.{{ cluster_fqdn }}'"
