---
- name: Create directory
  file:
    path: /tmp/{{ cluster_domain }}/platform/kong/{{ kong_name }}
    state: directory

- name: Copy namespace
  copy:
    src: ns.yaml
    dest: /tmp/{{ cluster_domain }}/platform/kong/ns.yaml

- name: Copy base kustomization if doesn't exist
  copy:
    src: base-kustomization.yaml
    dest: /tmp/{{ cluster_domain }}/platform/kong/kustomization.yaml
    force: false

- name: Process config-secret template
  template:
    src: config-secret.j2
    dest: /tmp/{{ cluster_domain }}/platform/kong/{{ kong_name }}/config-secret.yaml

- name: Convert config-secret to SealedSecret
  when: "'dry-run' not in ansible_run_tags"
  shell: |
    kubeseal --format=yaml </tmp/{{ cluster_domain }}/platform/kong/{{ kong_name }}/config-secret.yaml >/tmp/{{ cluster_domain }}/platform/kong/{{ kong_name }}/config-secret.tmp
    mv /tmp/{{ cluster_domain }}/platform/kong/{{ kong_name }}/config-secret.tmp /tmp/{{ cluster_domain }}/platform/kong/{{ kong_name }}/config-secret.yaml

- name: Process release template
  template:
    src: release.j2
    dest: /tmp/{{ cluster_domain }}/platform/kong/{{ kong_name }}/release.yaml

- name: Copy kong instance kustomization
  template:
    src: instance-kustomization.j2
    dest: /tmp/{{ cluster_domain }}/platform/kong/{{ kong_name }}/kustomization.yaml

- name: Add Kong instance to base kustomization
  lineinfile:
    path: /tmp/{{ cluster_domain }}/platform/kong/kustomization.yaml
    insertafter: '^/troubadour-base/kong/'
    line: '  - {{ kong_name }}/'

- name: Apply manifests
  when: "'dry-run' not in ansible_run_tags"
  with_ms3_inc.troubadour.kustomize: /tmp/{{ cluster_domain }}/platform/kong/
  k8s:
    definition: "{{ item }}"
    wait: true
    wait_condition: "{{ wait_conditions[item.kind] }}"

- name: Process flux-kustomization template
  template:
    src: flux-kustomization.j2
    dest: /tmp/{{ cluster_domain }}/platform/flux-system/watches/kong.yaml
    force: false
