---
- include_tasks: create_kong.yaml
  tags: [ requires_cluster ]
  when: cluster_state == 'present'

- include_tasks: delete_kong.yaml
  tags: [ requires_cluster ]
  when: cluster_state == 'absent'
