---
- name: Create Directories
  file:
    path: /tmp/{{ cluster_domain }}/platform/kong/{{ item.name }}
    state: directory
  loop: "{{ kong.instances }}"

- name: Copy Namespace
  copy:
    src: ns.yaml
    dest: /tmp/{{ cluster_domain }}/platform/kong/ns.yaml

- name: Process base kustomization template
  template:
    src: base-kustomization.j2
    dest: /tmp/{{ cluster_domain }}/platform/kong/kustomization.yaml

- name: Process instance config-secret templates
  template:
    src: config-secret.j2
    dest: /tmp/{{ cluster_domain }}/platform/kong/{{ item.name }}/config-secret.yaml
  loop: "{{ kong.instances }}"

- name: Convert instance config-secrets to SealedSecrets
  when: ('dry-run' not in ansible_run_tags)
  shell: |
    kubeseal --format=yaml </tmp/{{ cluster_domain }}/platform/kong/{{ item.name }}/config-secret.yaml >/tmp/{{ cluster_domain }}/platform/kong/{{ item.name }}/config-secret.tmp
    mv /tmp/{{ cluster_domain }}/platform/kong/{{ item.name }}/config-secret.tmp /tmp/{{ cluster_domain }}/platform/kong/{{ item.name }}/config-secret.yaml
  loop: "{{ kong.instances }}"

- name: Process instance release templates
  template:
    src: release.j2
    dest: /tmp/{{ cluster_domain }}/platform/kong/{{ item.name }}/release.yaml
  loop: "{{ kong.instances }}"

- name: Process instance values templates
  template:
    src: values.j2
    dest: /tmp/{{ cluster_domain }}/platform/kong/{{ item.name }}/values.yaml
  loop: "{{ kong.instances }}"
  
- name: Process instance keycloak-config templates
  when: (item.ee.enabled)
  template:
    src: keycloak-config.j2
    dest: /tmp/{{ cluster_domain }}/platform/kong/{{ item.name }}/keycloak-config.json
  loop: "{{ kong.instances }}"

- name: Create ee-admin-gui-auth-secret.yaml from keycloak-config.json
  when: (item.ee.enabled)
  shell: |
    kubectl create secret generic {{ item.name }}-admin-gui-auth-conf -n kong --from-file=admin_gui_auth_conf=/tmp/{{ cluster_domain }}/platform/kong/{{ item.name }}/keycloak-config.json --dry-run=client -o yaml > /tmp/{{ cluster_domain }}/platform/kong/{{ item.name }}/ee-admin-gui-auth-secret.yaml
  loop: "{{ kong.instances }}"

- name: Kubeseal ee-admin-gui-auth-secrets
  when: (item.ee.enabled) and ('dry-run' not in ansible_run_tags)
  shell: |
    kubeseal --format=yaml </tmp/{{ cluster_domain }}/platform/kong/{{ item.name }}/ee-admin-gui-auth-secret.yaml >/tmp/{{ cluster_domain }}/platform/kong/{{ item.name }}/ee-admin-gui-auth-secret.tmp
    mv /tmp/{{ cluster_domain }}/platform/kong/{{ item.name }}/ee-admin-gui-auth-secret.tmp /tmp/{{ cluster_domain }}/platform/kong/{{ item.name }}/ee-admin-gui-auth-secret.yaml
    rm /tmp/{{ cluster_domain }}/platform/kong/{{ item.name }}/keycloak-config.json
  loop: "{{ kong.instances }}"

- name: Process ee-license-secret Templates
  template:
    src: ee-license-secret.j2
    dest: /tmp/{{ cluster_domain }}/platform/kong/{{ item.name }}-ee-license-secret.yaml
  loop: "{{ kong.ee_creds }}"

- name: Kubeseal ee-license-secret
  when: ('dry-run' not in ansible_run_tags)
  shell: |
    kubeseal --format=yaml </tmp/{{ cluster_domain }}/platform/kong/{{ item.name }}-ee-license-secret.yaml >/tmp/{{ cluster_domain }}/platform/kong/{{ item.name }}-ee-license-secret.tmp
    mv /tmp/{{ cluster_domain }}/platform/kong/{{ item.name }}-ee-license-secret.tmp /tmp/{{ cluster_domain }}/platform/kong/{{ item.name }}-ee-license-secret.yaml
  loop: "{{ kong.ee_creds }}"

- name: Create ee-docker-secret
  shell: |
    kubectl create secret docker-registry {{ item.name }}-kong-enterprise-edition-docker -n kong \
    --docker-server=kong-docker-kong-enterprise-edition-docker.bintray.io \
    --docker-username="{{ item.image_registry.username }}" \
    --docker-password="{{ item.image_registry.password }}" \
    --dry-run=client -o yaml > /tmp/{{ cluster_domain }}/platform/kong/{{ item.name }}-ee-docker-secret.yaml
  loop: "{{ kong.ee_creds }}"

- name: Kubeseal ee-docker-secret
  when: ('dry-run' not in ansible_run_tags)
  shell: |
    kubeseal --format=yaml </tmp/{{ cluster_domain }}/platform/kong/{{ item.name }}-ee-docker-secret.yaml >/tmp/{{ cluster_domain }}/platform/kong/{{ item.name }}-ee-docker-secret.tmp
    mv /tmp/{{ cluster_domain }}/platform/kong/{{ item.name }}-ee-docker-secret.tmp /tmp/{{ cluster_domain }}/platform/kong/{{ item.name }}-ee-docker-secret.yaml
  loop: "{{ kong.ee_creds }}"

- name: Process instance ee-superuser-secret templates
  when: (item.ee.enabled)
  template:
    src: ee-superuser-secret.j2
    dest: /tmp/{{ cluster_domain }}/platform/kong/{{ item.name }}/ee-superuser-secret.yaml
  loop: "{{ kong.instances }}"

- name: Kubeseal instance ee-superuser-secret's
  when: (item.ee.enabled) and ('dry-run' not in ansible_run_tags)
  shell: |
    kubeseal --format=yaml </tmp/{{ cluster_domain }}/platform/kong/{{ item.name }}/ee-superuser-secret.yaml >/tmp/{{ cluster_domain }}/platform/kong/{{ item.name }}/ee-superuser-secret.tmp
    mv /tmp/{{ cluster_domain }}/platform/kong/{{ item.name }}/ee-superuser-secret.tmp /tmp/{{ cluster_domain }}/platform/kong/{{ item.name }}/ee-superuser-secret.yaml
  loop: "{{ kong.instances }}"

- name: Process instance ee-session-secret templates
  when: (item.ee.enabled)
  template:
    src: ee-session-secret.j2
    dest: /tmp/{{ cluster_domain }}/platform/kong/{{ item.name }}/ee-session-secret.yaml
  loop: "{{ kong.instances }}"

- name: Kubeseal instance ee-session-secret's
  when: (item.ee.enabled) and ('dry-run' not in ansible_run_tags)
  shell: |
    kubeseal --format=yaml </tmp/{{ cluster_domain }}/platform/kong/{{ item.name }}/ee-session-secret.yaml >/tmp/{{ cluster_domain }}/platform/kong/{{ item.name }}/ee-session-secret.tmp
    mv /tmp/{{ cluster_domain }}/platform/kong/{{ item.name }}/ee-session-secret.tmp /tmp/{{ cluster_domain }}/platform/kong/{{ item.name }}/ee-session-secret.yaml
  loop: "{{ kong.instances }}"

- name: Process instance kustomization templates
  template:
    src: instance-kustomization.j2
    dest: /tmp/{{ cluster_domain }}/platform/kong/{{ item.name }}/kustomization.yaml
  loop: "{{ kong.instances }}"

- name: Process instance ingresses templates
  when: (item.ee.enabled)
  template:
    src: ingresses.j2
    dest: /tmp/{{ cluster_domain }}/platform/kong/{{ item.name }}/ingresses.yaml
  loop: "{{ kong.instances }}"

- name: Apply manifests
  when: ('dry-run' not in ansible_run_tags)
  with_ms3_inc.troubadour.kustomize: /tmp/{{ cluster_domain }}/platform/kong/
  k8s:
    definition: "{{ item }}"
    wait: true
    wait_condition: "{{ wait_conditions[item.kind] | default(omit) }}"
    wait_timeout: 300

- name: Process flux-kustomization template
  template:
    src: flux-kustomization.j2
    dest: /tmp/{{ cluster_domain }}/platform/flux-system/watches/kong.yaml
    force: false
