---
- name: Create Directories
  file:
    path: /tmp/{{ cluster_fqdn }}/platform/kong/{{ item.name }}
    state: directory
  loop: "{{ kong.instances }}"

- include_tasks: generate-variables.yaml

- name: Template Files
  template:
    src: "{{ item.name }}.j2"
    dest: /tmp/{{ cluster_fqdn }}/platform/kong/{{ item.dest | default(item.name) }}.yaml
  when: item.condition | default(true)
  loop:
    - name: base-kustomization
      dest: kustomization

- name: Copy Files
  copy:
    src: "{{ item.name }}"
    dest: /tmp/{{ cluster_fqdn }}/platform/kong/{{ item.dest | default(item.name) }}
  when: item.condition | default(true)
  loop:
    - name: ns.yaml
    - name: helmrepo.yaml

- include_tasks: process-instances.yaml
  when: kong.instances

- include_tasks: process-ee-creds.yaml
  when: kong.ee_creds

- name: Apply Resources
  tags: [ requires_cluster ]
  when: ('dry-run' not in ansible_run_tags)
  loop: "{{ lookup('ms3_inc.tavros.kustomize', '/tmp/' + cluster_fqdn + '/platform/kong/', reorder='none') }}"
  loop_control:
    label: "{{ item.kind }}/{{ item.metadata.name | default('unnamed')}}"
  ms3_inc.tavros.kube:
    kubeconfig: '~/.kube/config'
    definition: "{{ item }}"
    wait: true
    wait_condition: "{{ wait_conditions[item.kind] | default(omit) }}"
    wait_timeout: 900

- name: Wait for LoadBalancer IPs
  tags: [ requires_cluster ]
  when: ('dry-run' not in ansible_run_tags)
  ms3_inc.tavros.kube_info:
    kubeconfig: '~/.kube/config'
    kind: Service
    name: "{{ instance_kong_proxy }}"
    namespace: kong
    wait: true
  retries: 30
  delay: 30
  changed_when: false
  vars:
    instance_kong_proxy: "kong-tavros-{{ item.name }}-kong-proxy"
  loop: "{{ kong.instances }}"

- name: Template flux-kustomization
  template:
    src: flux-kustomization.j2
    dest: /tmp/{{ cluster_fqdn }}/platform/flux-system/watches/kong.yaml
