---
- name: Create directories
  file:
    path: /tmp/{{ cluster_domain }}/platform/kong/{{ item.kong_name }}
    state: directory
  loop: "{{ kongs }}"

- name: Copy namespace
  copy:
    src: ns.yaml
    dest: /tmp/{{ cluster_domain }}/platform/kong/ns.yaml

- name: Copy base kustomization if doesn't exist
  copy:
    src: base-kustomization.yaml
    dest: /tmp/{{ cluster_domain }}/platform/kong/kustomization.yaml
    force: false

- name: Process config-secret templates
  template:
    src: config-secret.j2
    dest: /tmp/{{ cluster_domain }}/platform/kong/{{ item.kong_name }}/config-secret.yaml
  loop: "{{ kongs }}"

- name: Convert config-secrets to SealedSecrets
  when: "'dry-run' not in ansible_run_tags"
  shell: |
    kubeseal --format=yaml </tmp/{{ cluster_domain }}/platform/kong/{{ item.kong_name }}/config-secret.yaml >/tmp/{{ cluster_domain }}/platform/kong/{{ item.kong_name }}/config-secret.tmp
    mv /tmp/{{ cluster_domain }}/platform/kong/{{ item.kong_name }}/config-secret.tmp /tmp/{{ cluster_domain }}/platform/kong/{{ item.kong_name }}/config-secret.yaml
  loop: "{{ kongs }}"

- name: Process release templates
  template:
    src: release.j2
    dest: /tmp/{{ cluster_domain }}/platform/kong/{{ item.kong_name }}/release.yaml
  loop: "{{ kongs }}"

- name: Process instance kustomization templates
  template:
    src: instance-kustomization.j2
    dest: /tmp/{{ cluster_domain }}/platform/kong/{{ item.kong_name }}/kustomization.yaml
  loop: "{{ kongs }}"

- name: Add Kong instances to base kustomization
  lineinfile:
    path: /tmp/{{ cluster_domain }}/platform/kong/kustomization.yaml
    insertafter: '^/troubadour-base/kong/'
    line: '  - {{ item.kong_name }}/'
  loop: "{{ kongs }}"

- name: Apply manifests
  when: "'dry-run' not in ansible_run_tags"
  with_ms3_inc.troubadour.kustomize: /tmp/{{ cluster_domain }}/platform/kong/
  k8s:
    definition: "{{ item }}"
    wait: true
    wait_condition: "{{ wait_conditions[item.kind] | default(omit) }}"

- name: Process flux-kustomization template
  template:
    src: flux-kustomization.j2
    dest: /tmp/{{ cluster_domain }}/platform/flux-system/watches/kong.yaml
    force: false
