---
- name: Template EE Creds Files
  template:
    src: "{{ item[1].name }}.j2"
    dest: /tmp/{{ cluster_fqdn }}/platform/kong/{{ item[0].name }}-{{ item[1].dest | default(item[1].name) }}.yaml
  with_nested:
    - "{{ kong.ee_creds }}"
    -
      - name: secret-ee-license

  # todo: fit this template into the generic loops above
- name: Template secret-ee-registry
  template:
    src: secret-ee-registry.j2
    dest: /tmp/{{ cluster_fqdn }}/platform/kong/{{ item.name }}-secret-ee-registry.yaml
  vars:
    config:
      auths:
        kong-docker-kong-enterprise-edition-docker.bintray.io:
          auth: "{{ (item.image_registry.username + ':' + item.image_registry.password) | b64encode }}"
  loop: "{{ kong.ee_creds }}"

- name: Seal EE Creds Secrets
  tags: [ requires_cluster ]
  shell: |
    kubeseal --format=yaml </tmp/{{ cluster_fqdn }}/platform/kong/{{ item[0].name }}-{{ item[1].name }}.yaml >/tmp/{{ cluster_fqdn }}/platform/kong/{{ item[0].name }}-{{ item[1].name }}.tmp
    mv /tmp/{{ cluster_fqdn }}/platform/kong/{{ item[0].name }}-{{ item[1].name }}.tmp /tmp/{{ cluster_fqdn }}/platform/kong/{{ item[0].name }}-{{ item[1].name }}.yaml
  with_nested:
    - "{{ kong.ee_creds }}"
    -
      - name: secret-ee-license
      - name: secret-ee-registry
