---
- name: Assert Required Binaries are Available
  shell: |
    kubectl version
    kustomize version
    flux --version
    kubeseal --version
  changed_when: false

- name: Install Required Python Modules
  pip:
    extra_args: --user
    name:
      - boto
      - boto3
      - botocore
      # see: https://github.com/kubernetes-client/python/issues/1333
      # https://github.com/openshift/openshift-restclient-python/issues/398
      - kubernetes==11.0.0
      - openshift==0.11.2

- set_fact:
    wait_conditions:
      HelmRelease:
        type: Ready
        status: true
        reason: ReconciliationSucceeded

- name: Configure Git User
  shell: |
    git config --global user.email
    if [ $? -ne 0 ]; then
      git config --global user.email "{{ cluster_admin_email }}"
      git config --global user.name "tavros/provision_playbook"
    fi

- name: Configure Git SSL-Verify
  when: "'test-run' in ansible_run_tags"
  shell: |
    git config --global http.sslVerify false
