---
- name: Assert Required Binaries are Available
  shell: |
    kubectl version
    kustomize version
    flux --version
    kubeseal --version
  changed_when: false

- name: Install Required Python Modules
  pip:
    extra_args: --user
    name:
      - boto
      - boto3
      - botocore
      - openshift

- name: Configure git user email
  shell: |
    git config --global user.email
    if [ $? -ne 0 ]; then
      git config --global user.email "{{ cluster_admin_email }}"
      git config --global user.name "Tavros Installer"
    fi

- set_fact:
    wait_conditions:
      HelmRelease:
        type: Ready
        status: true
        reason: ReconciliationSucceeded
