---
- name: Set kubernetes_cluster Default Variables
  set_fact:
    kubernetes_cluster: "{{ defaults | combine(kubernetes_cluster, recursive=true)  }}"
  vars:
    defaults:
      dns_zone: "{{ cluster_fqdn }}"

- name: Add Custom wait_conditions
  set_fact:
    wait_conditions:
      HelmRelease:
        type: Ready
        status: true
        reason: ReconciliationSucceeded

- name: Configure Git User
  shell: |
    git config --global user.email
    if [ $? -ne 0 ]; then
      git config --global user.email "{{ cluster_admin_email }}"
      git config --global user.name "tavros/provision_playbook"
    fi

- name: Disable Git SSL-Verify
  when: "'test-run' in ansible_run_tags"
  shell: |
    git config --global http.sslVerify false
