apiVersion: v1
kind: Service
metadata:
  name: tavros-container-registry
  namespace: nexus
spec:
  selector:
    app.kubernetes.io/instance: tavros
    app.kubernetes.io/name: nexus-repository-manager
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: ClusterIP
  sessionAffinity: None
