---
- name: Create directory
  file:
    path: ./{{ cluster_domain }}/platform/keycloak
    state: directory

- name: Process keycloak-db-secret template
  template:
    src: keycloak-db-secret.j2
    dest: ./{{ cluster_domain }}/platform/keycloak/keycloak-db-secret.yaml

- name: Convert keycloak-db-secret to SealedSecret
  shell: |
    kubeseal --format=yaml <./{{ cluster_domain }}/platform/keycloak/keycloak-db-secret.yaml >./{{ cluster_domain }}/platform/keycloak/keycloak-db-secret.tmp
    mv ./{{ cluster_domain }}/platform/keycloak/keycloak-db-secret.tmp ./{{ cluster_domain }}/platform/keycloak/keycloak-db-secret.yaml

- name: Copy keycloak kustomization
  copy:
    src: kustomization.yaml
    dest: ./{{ cluster_domain }}/platform/keycloak/kustomization.yaml

- name: Apply operator manifests
  shell: |
    kustomize build ./troubadour-base/keycloak/operator | kubectl apply -f -

- name: Wait for keycloak operator
  shell: |
    kubectl -n keycloak wait --for=condition=available --timeout=120s deployments --all
    kubectl -n keycloak wait --for=condition=ready --timeout=120s pods --all

- name: Apply keycloak manifests
  shell: |
    kustomize build ./{{ cluster_domain }}/platform/keycloak/ | kubectl apply -f -

- name: Wait for keycloak
  shell: |
    kubectl -n keycloak wait --for=condition=available --timeout=120s deployments --all
    kubectl -n keycloak wait --for=condition=ready --timeout=120s pods --all