apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tavros
  namespace: cert-manager
spec:
  targetNamespace: cert-manager
  interval: 10m
  chart:
    spec:
      # https://github.com/jetstack/cert-manager/blob/v1.3.0/deploy/charts/cert-manager/values.yaml
      chart: cert-manager
      version: 1.3.0
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    installCRDs: true
