---
- name: Delete a managed Azure Container Services (AKS) instance
  collections:
    - azure.azcollection
  azure_rm_aks:
    name: "{{ aks.name }}"
    kubernetes_version: 1.21.2
    location: eastus
    dns_prefix: "{{ aks.name }}"
    enable_rbac: true
    resource_group: "{{ aks.resource_group }}"
    state: absent