---
- name: Create directory
  file:
    path: /tmp/{{ cluster_domain }}/platform/gitea
    state: directory

- name: Copy Gitea ns
  copy:
    src: ns.yaml
    dest: /tmp/{{ cluster_domain }}/platform/gitea/ns.yaml

- name: Generate Admin pass for Gitea
  when: gitea.admin.password is not defined
  set_fact:
    gitea: "{{ gitea | combine({ 'admin': { 'password': lookup('password', '/dev/null') } } , recursive=true) }}"

- name: Process values-secret template
  template:
    src: values-secret.j2
    dest: /tmp/{{ cluster_domain }}/platform/gitea/values-secret.yaml

- name: Convert values-secret to SealedSecrets
  when: ('dry-run' not in ansible_run_tags)
  shell: |
    kubeseal --format=yaml </tmp/{{ cluster_domain }}/platform/gitea/values-secret.yaml >/tmp/{{ cluster_domain }}/platform/gitea/values-secret.tmp
    mv /tmp/{{ cluster_domain }}/platform/gitea/values-secret.tmp /tmp/{{ cluster_domain }}/platform/gitea/values-secret.yaml

- name: Copy gitea kustomization
  copy:
    src: kustomization.yaml
    dest: /tmp/{{ cluster_domain }}/platform/gitea/kustomization.yaml

- name: Copy gitea helm source
  copy:
    src: helm-source.yaml
    dest: /tmp/{{ cluster_domain }}/platform/gitea/helm-source.yaml

- name: Copy gitea release
  copy:
    src: release.yaml
    dest: /tmp/{{ cluster_domain }}/platform/gitea/release.yaml

- name: Process ingress template
  template:
    src: ingress.j2
    dest: /tmp/{{ cluster_domain }}/platform/gitea/ingress.yaml

- name: Process flux-kustomization template
  template:
    src: flux-kustomization.j2
    dest: /tmp/{{ cluster_domain }}/platform/flux-system/watches/gitea.yaml

- name: Process instance keycloak-client templates
  template:
    src: keycloak-client.j2
    dest: /tmp/{{ cluster_domain }}/platform/gitea/keycloak-client.yaml

- name: Apply manifests
  when: ('dry-run' not in ansible_run_tags)
  loop: "{{ lookup('ms3_inc.troubadour.kustomize', '/tmp/' + cluster_domain + '/platform/gitea/', reorder='none') }}"
  k8s:
    definition: "{{ item }}"
    wait: true
    wait_condition: "{{ wait_conditions[item.kind] | default(omit) }}"
    wait_timeout: 1800

- include_tasks: keycloak_sso.yaml

- name: Add tavros organization
  uri:
    url: https://code.{{ cluster_name }}.{{ cluster_domain }}/api/v1/orgs
    method: POST
    force_basic_auth: true
    follow_redirects: all
    body_format: json
    url_username: gitea_admin
    url_password: '{{ gitea.admin.password }}'
    body:
      username: tavros
      visibility: limited
      repo_admin_change_team_access: true
    status_code: 201
