---
- name: Create directory
  file:
    path: /tmp/{{ cluster_domain }}/platform/gitea
    state: directory

- name: Set gitea_admin_pass
  set_fact:
    gitea_admin_pass: "{{ lookup('password', '/dev/null') }}"

- name: Process values template
  template:
    src: values.j2
    dest: /tmp/{{ cluster_domain }}/platform/gitea/overlay-values.yaml

- name: Convert overlay-values to Secret
  when: "'dry-run' not in ansible_run_tags"
  shell: |
    kubectl create secret generic overlay-values-secret --dry-run=client --from-file=values.yaml=/tmp/{{ cluster_domain }}/platform/gitea/overlay-values.yaml -n gitea -o yaml >/tmp/{{ cluster_domain }}/platform/gitea/overlay-values-secret.yaml
    rm /tmp/{{ cluster_domain }}/platform/gitea/overlay-values.yaml

- name: Convert overlay-values-secret to SealedSecret
  when: "'dry-run' not in ansible_run_tags"
  shell: |
    kubeseal --format=yaml </tmp/{{ cluster_domain }}/platform/gitea/overlay-values-secret.yaml >/tmp/{{ cluster_domain }}/platform/gitea/overlay-values-secret.tmp
    mv /tmp/{{ cluster_domain }}/platform/gitea/overlay-values-secret.tmp /tmp/{{ cluster_domain }}/platform/gitea/overlay-values-secret.yaml

- name: Copy Gitea HelmChart patch
  copy:
    src: patch.json
    dest: /tmp/{{ cluster_domain }}/platform/gitea/patch.json

- name: Copy gitea kustomization
  copy:
    src: kustomization.yaml
    dest: /tmp/{{ cluster_domain }}/platform/gitea/kustomization.yaml

- name: Copy gitea helm source
  copy:
    src: helm-source.yaml
    dest: /tmp/{{ cluster_domain }}/platform/gitea/helm-source.yaml

- name: Copy gitea release
  copy:
    src: release.yaml
    dest: /tmp/{{ cluster_domain }}/platform/gitea/release.yaml

- name: Copy gitea release values
  copy:
    src: values.yaml
    dest: /tmp/{{ cluster_domain }}/platform/gitea/values.yaml

- name: Apply gitea manifests
  when: "'dry-run' not in ansible_run_tags"
  shell: |
    kustomize build /tmp/{{ cluster_domain }}/platform/gitea/ | kubectl apply -f -

- name: Wait for Gitea Helmrealse, Deployment, and Pods
  when: "'dry-run' not in ansible_run_tags"
  shell: |
    kubectl -n gitea wait --for=condition=ready --timeout=120s helmrelease.helm.toolkit.fluxcd.io --all
    kubectl -n gitea wait --for=condition=available --timeout=120s deployments --all
    kubectl -n gitea wait --for=condition=ready --timeout=120s pods --all

- name: Process flux-kustomization template
  template:
    src: flux-kustomization.j2
    dest: /tmp/{{ cluster_domain }}/platform/flux-system/watches/gitea.yaml
