---
- name: Create directory
  file:
    path: /tmp/{{ cluster_domain }}/platform/kubeseal
    state: directory

- name: Copy kubeseal kustomization
  copy:
    src: kustomization.yaml
    dest: /tmp/{{ cluster_domain }}/platform/kubeseal/kustomization.yaml

- name: Apply kubeseal manifests
  when: "'dry-run' not in ansible_run_tags"
  with_ms3_inc.troubadour.kustomize: /tmp/{{ cluster_domain }}/platform/kubeseal/
  k8s:
    definition: "{{ item }}"
    wait: true

- name: Process flux-kustomization template
  template:
    src: flux-kustomization.j2
    dest: /tmp/{{ cluster_domain }}/platform/flux-system/watches/kubeseal.yaml
