---
- name: Create directory
  file:
    path: /tmp/{{ cluster_fqdn }}/platform/kubeseal
    state: directory

- name: Copy Files
  copy:
    src: "{{ item.name }}"
    dest: /tmp/{{ cluster_fqdn }}/platform/kubeseal/{{ item.name }}
  when: item.condition | default(true)
  loop:
    - name: kustomization.yaml

- name: Apply Resources
  when: ('dry-run' not in ansible_run_tags)
  loop: "{{ lookup('ms3_inc.tavros.kustomize', '/tmp/' + cluster_fqdn + '/platform/kubeseal/', reorder='none') }}"
  k8s:
    definition: "{{ item }}"
    wait: true
    wait_condition: "{{ wait_conditions[item.kind] | default(omit) }}"
    wait_timeout: 900

- name: Template flux-kustomization
  template:
    src: flux-kustomization.j2
    dest: /tmp/{{ cluster_fqdn }}/platform/flux-system/watches/kubeseal.yaml
