CREATE DATABASE gitea;
CREATE USER gitea WITH ENCRYPTED PASSWORD 'gitea';
GRANT ALL PRIVILEGES ON DATABASE gitea TO gitea;

CREATE DATABASE kong;
CREATE USER kong WITH ENCRYPTED PASSWORD 'kong';
GRANT ALL PRIVILEGES ON DATABASE kong TO kong;

CREATE DATABASE keycloak;
CREATE USER keycloak WITH ENCRYPTED PASSWORD 'keycloak';
GRANT ALL PRIVILEGES ON DATABASE keycloak TO keycloak;
