---
all:
  vars:
    cluster_fqdn: ''
    cluster_admin_email: ''
    kubernetes_cluster:
      cloud_provider: 'aws'
      master_count: 3
      master_instance_type: 't2.large'
      master_azs: 'us-east-1a,us-east-1b'
      worker_count: 2
      worker_instance_type: 't2.xlarge'
      worker_azs: 'us-east-1a,us-east-1b'
      dns_zone: "{{ cluster_fqdn }}"
    kops:
      enabled: true
      state_bucket: "{{ cluster_fqdn }}-tavros"
      state_bucket_region: "us-east-1"
    kong:
      default_ingress_class: 'prod'
      ee_creds: []
      instances:
      - name: 'sandbox-kong'
        ingress_class: 'sandbox'
        kuma_mesh_name: 'sandbox'
        ee:
          enabled: false
      - name: 'prod-kong'
        ingress_class: 'prod'
        kuma_mesh_name: 'prod'
        ee:
          enabled: false
    kuma:
      enabled: true
      meshes:
      - name: 'sandbox'
        mtls:
          enabled: true
        traffictrace:
          enabled: true
      - name: 'prod'
        mtls:
          enabled: true
        traffictrace:
          enabled: true
    namespaces:
    - name: 'dev'
      kuma_mesh_name: 'sandbox'
    - name: 'test'
      kuma_mesh_name: 'sandbox'
    - name: 'prod'
      kuma_mesh_name: 'prod'
    keycloak:
      enabled: true
      realms:
      - name: sandbox
      - name: prod
    postgresql: {}
    cert_manager:
      enabled: true
    gitea:
      enabled: true
      keycloak:
        realm: 'prod'
    nexus:
      enabled: true
      keycloak:
        realm: 'prod'
    elastic_cloud:
      ee:
        enabled: false
      enabled: true
    jaeger:
      enabled: true
      keycloak:
        realm: 'prod'
    jenkins:
      enabled: true
      keycloak:
        realm: 'prod'
    flux: {}
