---
type: object
properties:
  cluster_name:
    type: string
  cluster_domain:
    type: string
  cluster_admin_email:
    type: string
  kubernetes_cluster:
    type: object
    properties:
      cloud:
        type: string
      master_count:
        type: integer
      master_size:
        type: string
      node_count:
        type: integer
      node_size:
        type: string
      zones:
        type: string
      state_bucket:
        type: string
      ssh_public_key_path:
        type: string
      aws_access_key_id:
        type: string
      aws_secret_access_key:
        type: string
  kong:
    type: object
    properties:
      default_ingress_class:
        type: string
      ee_creds:
        type: array
        items:
          type: object
          properties:
            name:
              type: string
            license:
              type: string
            image_registry:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      instances:
        type: array
        items:
          type: object
          properties:
            name:
              type: string
            ingress_class:
              type: string
            kuma_mesh_name:
              type: string
            ee:
              type: object
              properties:
                enabled:
                  type: boolean
                creds:
                  type: string
                admin_password:
                  type: string
                keycloak:
                  type: object
                  properties:
                    realm:
                      type: string
                    client_secret:
                      type: string
            pg:
              type: object
              properties:
                password:
                  type: string
  kuma:
    type: object
    properties:
      meshes:
        type: array
        items:
          type: object
          properties:
            name:
              type: string
            mtls:
              type: object
              properties:
                enabled:
                  type: boolean
            traffictrace:
              type: object
              properties:
                enabled:
                  type: boolean
  namespaces:
    type: array
    items:
      type: object
      properties:
        name:
          type: string
        kuma_mesh_name:
          type: string
  keycloak:
    type: object
    properties:
      enabled:
        type: boolean
      pg:
        type: object
        properties:
          password:
            type: string
      realms:
        type: array
        items:
          type: object
          properties:
            name:
              type: string
            admin_password:
              type: string
  postgresql:
    type: object
    properties:
      password:
        type: string
      postgres_password:
        type: string
  cert_manager:
    type: object
    properties:
      enabled:
        type: boolean
  gitea:
    type: object
    properties:
      enabled:
        type: boolean
      keycloak:
        type: object
        properties:
          realm:
            type: string
          client_secret:
            type: string
  nexus:
    type: object
    properties:
      enabled:
        type: boolean
      keycloak:
        type: object
        properties:
          realm:
            type: string
          client_secret:
            type: string
  elastic_cloud:
    type: object
    properties:
      enabled:
        type: boolean
      elastic_secret:
        type: string
      ee:
        type: object
        properties:
          enabled:
            type: boolean
          trial:
            type: boolean
          keycloak:
            type: object
            properties:
              realm:
                type: string
              client_secret:
                type: string
          licnese:
            type: string
  jaeger:
    type: object
    properties:
      enabled:
        type: boolean
      keycloak:
        type: object
        properties:
          realm:
            type: string
          client_secret:
            type: string
  jenkins:
    type: object
    properties:
      enabled:
        type: boolean
      keycloak:
        type: object
        properties:
          realm:
            type: string