---
type: object
properties:
  cluster_fqdn:
    type: string
  cluster_admin_email:
    type: string
  kubernetes_cluster:
    type: object
    properties:
      cloud_provider:
        type: string
      dns_zone:
        type: string
      keycloak:
        type: object
        properties:
          realm:
            type: string
          client_secret:
            type: string
  kops:
    type: object
    properties:
      enabled:
        type: boolean
      master_count:
        type: integer
      master_size:
        type: string
      master_zones:
        type: string
      node_count:
        type: integer
      node_size:
        type: string
      node_zones:
        type: string
      state_bucket:
        type: string
      state_bucket_region:
        type: string
    required:
    - enabled
  kong:
    type: object
    properties:
      enabled:
        type: boolean
      default_ingress_class:
        type: string
      ee_creds:
        type: array
        items:
          type: object
          properties:
            name:
              type: string
            license:
              type: string
      instances:
        type: array
        items:
          type: object
          properties:
            name:
              type: string
            hybrid:
              type: boolean
            ingress_class:
              type: string
            kuma_mesh_name:
              type: string
            pg:
              type: object
              properties:
                password:
                  type: string
            ee:
              type: object
              properties:
                enabled:
                  type: boolean
                creds:
                  type: string
              required:
              - enabled
          required:
          - name
          - ingress_class
    required:
    - enabled
  kuma:
    type: object
    properties:
      enabled:
        type: boolean
      meshes:
        type: array
        items:
          type: object
          properties:
            name:
              type: string
            mtls:
              type: object
              properties:
                enabled:
                  type: boolean
              required:
              - enabled
            traffictrace:
              type: object
              properties:
                enabled:
                  type: boolean
              required:
              - enabled
          required:
          - name
    required:
    - enabled
  namespaces:
    type: array
    items:
      type: object
      properties:
        name:
          type: string
        kuma_mesh_name:
          type: string
      required:
      - name
  keycloak:
    type: object
    properties:
      enabled:
        type: boolean
      pg:
        type: object
        properties:
          password:
            type: string
      realms:
        type: array
        items:
          type: object
          properties:
            name:
              type: string
            admin_password:
              type: string
          required:
          - name
    required:
    - enabled
  postgresql:
    type: object
    properties:
      password:
        type: string
      postgres_password:
        type: string
  cert_manager:
    type: object
    properties:
      enabled:
        type: boolean
    required:
    - enabled
  gitea:
    type: object
    properties:
      enabled:
        type: boolean
      admin_password:
        type: string
      pg:
        type: object
        properties:
          password:
            type: string
      keycloak:
        type: object
        properties:
          realm:
            type: string
          client_secret:
            type: string
        required:
        - realm
    required:
    - enabled
  nexus:
    type: object
    properties:
      enabled:
        type: boolean
      keycloak:
        type: object
        properties:
          realm:
            type: string
          client_secret:
            type: string
        required:
        - realm
    required:
    - enabled
  elastic_cloud:
    type: object
    properties:
      enabled:
        type: boolean
      ee:
        type: object
        properties:
          enabled:
            type: boolean
          trial:
            type: boolean
          keycloak:
            type: object
            properties:
              realm:
                type: string
              client_secret:
                type: string
            required:
            - realm
          license:
            type: string
        required:
        - enabled
    required:
    - enabled
  jaeger:
    type: object
    properties:
      enabled:
        type: boolean
      keycloak:
        type: object
        properties:
          realm:
            type: string
          client_secret:
            type: string
        required:
        - realm
      es:
        type: object
        properties:
          password:
            type: string
    required:
    - enabled
  jenkins:
    type: object
    properties:
      enabled:
        type: boolean
      keycloak:
        type: object
        properties:
          realm:
            type: string
          password:
            type: string
        required:
        - realm
      gitea:
        type: object
        properties:
          password:
            type: string
    required:
    - enabled
  flux:
    type: object
    properties:
      gitea:
        type: object
        properties:
          password:
            type: string
required:
- cluster_fqdn
- cluster_admin_email
