apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
resources:
- ns.yaml
- https://raw.githubusercontent.com/keycloak/keycloak-operator/12.0.4/deploy/crds/keycloak.org_keycloakbackups_crd.yaml
- https://raw.githubusercontent.com/keycloak/keycloak-operator/12.0.4/deploy/crds/keycloak.org_keycloakclients_crd.yaml
- https://raw.githubusercontent.com/keycloak/keycloak-operator/12.0.4/deploy/crds/keycloak.org_keycloakrealms_crd.yaml
- https://raw.githubusercontent.com/keycloak/keycloak-operator/12.0.4/deploy/crds/keycloak.org_keycloaks_crd.yaml
- https://raw.githubusercontent.com/keycloak/keycloak-operator/12.0.4/deploy/crds/keycloak.org_keycloakusers_crd.yaml
- https://raw.githubusercontent.com/keycloak/keycloak-operator/12.0.4/deploy/role.yaml
- https://raw.githubusercontent.com/keycloak/keycloak-operator/12.0.4/deploy/role_binding.yaml
- https://raw.githubusercontent.com/keycloak/keycloak-operator/12.0.4/deploy/service_account.yaml
- https://raw.githubusercontent.com/keycloak/keycloak-operator/12.0.4/deploy/operator.yaml
