apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../troubadour-base/gitea/
configMapGenerator:
  - name: overlay-values-config
    namespace: gitea
    files:
      - values.yaml=values.yaml
generatorOptions:
  disableNameSuffixHash: true
patches:
- target:
    kind: HelmRelease
    name: gitea
  path: patch.json