---
- name: Delete Cluster
  when: (cluster_state == 'absent') and ('dry-run' not in ansible_run_tags)
  register: result
  changed_when: result.rc == 101
  failed_when: (result.rc != 100) and (result.rc != 101)
  shell: |
    kops get cluster \
        --name {{ cluster_fqdn }} \
        --state s3://{{ kubernetes_cluster.state_bucket }}/{{ cluster_fqdn }}/kops

    if [[ $? -eq 0 ]]; then
      kops delete cluster \
        --name="{{ cluster_fqdn }}" \
        --state="s3://{{ kubernetes_cluster.state_bucket }}/{{ cluster_fqdn }}/kops" \
        --yes
      if [ $? -ne 0 ]; then { echo "Failed to delete cluster"; exit 1; } fi
      exit 101
    fi

    exit 100

- name: Delete kOps S3 Bucket
  when: (cluster_state == 'absent') and ('dry-run' not in ansible_run_tags)
  amazon.aws.aws_s3:
    bucket: "{{ kubernetes_cluster.state_bucket }}"
    mode: delete
