---
- name: Store Tavros Vars
  tags: [ requires_cluster ]
  when: (kubernetes_cluster.cloud == 'aws')
  amazon.aws.aws_s3:
    bucket: "{{ kubernetes_cluster.state_bucket }}"
    object: /{{ cluster_fqdn }}/vars.yaml
    src: /tmp/{{ cluster_fqdn }}_vars.yaml
    mode: put
