---
# todo: should this live in the gitea role?
# this should be changed to not add a password and subsequently add a personal tokens
# this is blocked by lack of support of plain secret credentials by the jenkins gitea plugin
# we can workaround that by adding a kubernetes to gitea token credential converter
# see: https://www.jenkins.io/doc/developer/extensions/kubernetes-credentials-provider/
# https://github.com/jenkinsci/gitea-plugin/blob/gitea-1.2.1/src/main/java/org/jenkinsci/plugin/gitea/credentials/PersonalAccessToken.java
- name: Create Local Gitea jenkins-ci User
  tags: [ requires_cluster, non_idempotent, jenkins ]
  when: ('dry-run' not in ansible_run_tags)
  uri:
    url: https://code.{{ cluster_fqdn }}/api/v1/admin/users
    method: POST
    force_basic_auth: true
    follow_redirects: all
    body_format: json
    url_username: gitea_admin
    url_password: '{{ gitea.admin_password }}'
    body:
      username: jenkins-ci
      email: "jenkins-ci@{{ cluster_fqdn }}"
      login_name: jenkins-ci
      must_change_password: false
      password: "{{ jenkins.gitea.password }}"
      send_notify: false
      # this points to Keycloak as local is source_id 0
      source_id: 1
    status_code: 201
    validate_certs: False

- name: Register gitea_login Cookies Variable
  # todo: figure out how to re-use gitea_login if available
  # beware a simple `when` with a `register` will ovewrite the variable with the skipped task dict
  # when: gitea_login.cookies_string is not defined
  tags: [ requires_cluster, jenkins ]
  when: ('dry-run' not in ansible_run_tags)
  uri:
    url: https://code.{{ cluster_fqdn }}/user/login
    method: POST
    follow_redirects: all
    body_format: form-urlencoded
    body:
      user_name: gitea_admin
      password: '{{ gitea.admin_password }}'
    status_code: 200
    validate_certs: False
  register: gitea_login

- name: Add jenkins-ci as Owner of tavros/platform Repository
  tags: [ requires_cluster, non_idempotent, jenkins ]
  when: ('dry-run' not in ansible_run_tags)
  uri:
    url: https://code.{{ cluster_fqdn }}/org/tavros/teams/owners/action/add
    method: POST
    follow_redirects: all
    body_format: form-urlencoded
    headers:
      Cookie: "{{ gitea_login.cookies_string }}"
    body:
      _csrf: "{{ gitea_login.cookies._csrf }}"
      # gitea_admin uid
      uid: 1
      uname: jenkins-ci
    status_code: 200
    validate_certs: False
