---
- name: Create Directory
  file:
    path: /tmp/{{ cluster_fqdn }}/platform/jenkins/default
    state: directory

- name: Template Files
  template:
    src: "{{ item.name }}.j2"
    dest: /tmp/{{ cluster_fqdn }}/platform/jenkins/{{ item.dest | default(item.name) }}.yaml
  when: item.condition | default(true)
  loop:
    - name: configmap-jenkins-config
      dest: default/configmap-jenkins-config
    - name: ingress
      dest: default/ingress
    - name: keycloakclient
      dest: default/keycloakclient
    - name: keycloakuser-jenkins-ci
      dest: default/keycloakuser-jenkins-ci

- name: Template secret-artifacts-registry File
  template:
    src: secret-artifacts-registry.j2
    dest: /tmp/{{ cluster_fqdn }}/platform/jenkins/default/secret-artifacts-registry.yaml
  vars:
    config:
      auths: "{{ { 'registry.' + cluster_fqdn : { 'auth' : 'jenkins-ci:jenkins-ci' | b64encode } } }}"

- name: Copy Files
  copy:
    src: "{{ item.name }}"
    dest: /tmp/{{ cluster_fqdn }}/platform/jenkins/{{ item.dest | default(item.name) }}
  when: item.condition | default(true)
  loop:
    - name: base-kustomization.yaml
      dest: kustomization.yaml
    - name: instance-kustomization.yaml
      dest: default/kustomization.yaml
    - name: jenkins.yaml
      dest: default/jenkins.yaml
    - name: secret-gitea-creds.yaml
      dest: default/secret-gitea-creds.yaml
    - name: operator
      dest: ""

- name: Seal Secrets
  tags: [ requires_cluster ]
  when: item.condition | default(true)
  shell: |
    kubeseal --format=yaml </tmp/{{ cluster_fqdn }}/platform/jenkins/{{ item.name }}.yaml >/tmp/{{ cluster_fqdn }}/platform/jenkins/{{ item.name }}.tmp
    mv /tmp/{{ cluster_fqdn }}/platform/jenkins/{{ item.name }}.tmp /tmp/{{ cluster_fqdn }}/platform/jenkins/{{ item.name }}.yaml
  loop:
    - name: default/secret-gitea-creds
    - name: default/secret-artifacts-registry

- name: Apply Operator Resources
  tags: [ requires_cluster ]
  with_ms3_inc.tavros.kustomize:  /tmp/{{ cluster_fqdn }}/platform/jenkins/operator/0.5.0
  community.kubernetes.k8s:
    kubeconfig: '~/.kube/config'
    definition: "{{ item }}"
    wait: true
    wait_condition: "{{ wait_conditions[item.kind] | default(omit) }}"
    wait_timeout: 900

- name: Apply Resources
  tags: [ requires_cluster ]
  with_ms3_inc.tavros.kustomize:  /tmp/{{ cluster_fqdn }}/platform/jenkins
  community.kubernetes.k8s:
    kubeconfig: '~/.kube/config'
    definition: "{{ item }}"
    wait: true
    wait_condition: "{{ wait_conditions[item.kind] | default(omit) }}"
    wait_timeout: 900

- name: Wait for Jenkins
  tags: [ requires_cluster ]
  community.kubernetes.k8s_info:
    kubeconfig: '~/.kube/config'
    kind: Pod
    name: jenkins-tavros
    namespace: jenkins
    wait: true
    wait_timeout: 900
  changed_when: false

- include_tasks: gitea_setup.yaml

- name: Template flux-kustomization
  template:
    src: flux-kustomization.j2
    dest: /tmp/{{ cluster_fqdn }}/platform/flux-system/watches/jenkins.yaml
