---
- name: Create directory
  file:
    path: /tmp/{{ cluster_domain }}/platform/jenkins/default
    state: directory

- name: Copy operator
  copy:
    src: operator
    dest: /tmp/{{ cluster_domain }}/platform/jenkins/

- name: Copy jenkins ns
  copy:
    src: ns.yaml
    dest: /tmp/{{ cluster_domain }}/platform/jenkins/ns.yaml

- name: Copy base kustomization
  copy:
    src: base-kustomization.yaml
    dest: /tmp/{{ cluster_domain }}/platform/jenkins/kustomization.yaml

- name: Copy instance kustomization
  copy:
    src: instance-kustomization.yaml
    dest: /tmp/{{ cluster_domain }}/platform/jenkins/default/kustomization.yaml

- name: Process ingress template
  template:
    src: ingress.j2
    dest: /tmp/{{ cluster_domain }}/platform/jenkins/default/ingress.yaml

- name: Process configuration template
  template:
    src: config.j2
    dest: /tmp/{{ cluster_domain }}/platform/jenkins/default/config.yaml

- name: Process keycloak client template
  template:
    src: keycloak-client.j2
    dest: /tmp/{{ cluster_domain }}/platform/jenkins/default/keycloak-client.yaml

- name: Copy jenkins instance
  copy:
    src: default-instance.yaml
    dest: /tmp/{{ cluster_domain }}/platform/jenkins/default/instance.yaml

- name: Apply operator manifests
  when: ('dry-run' not in ansible_run_tags)
  with_ms3_inc.troubadour.kustomize:  /tmp/{{ cluster_domain }}/platform/jenkins/operator/0.5.0
  k8s:
    definition: "{{ item }}"
    wait: true
    wait_condition: "{{ wait_conditions[item.kind] | default(omit) }}"

- name: Apply manifests
  when: ('dry-run' not in ansible_run_tags)
  with_ms3_inc.troubadour.kustomize:  /tmp/{{ cluster_domain }}/platform/jenkins
  k8s:
    definition: "{{ item }}"
    wait: true
    wait_condition: "{{ wait_conditions[item.kind] | default(omit) }}"

- name: Wait for Jenkins
  when: ('dry-run' not in ansible_run_tags)
  community.kubernetes.k8s_info:
    kind: Pod
    name: jenkins-troubadour
    namespace: jenkins
    wait: true
    wait_sleep: 10
    wait_timeout: 3600
  changed_when: false

- name: Process flux-kustomization template
  template:
    src: flux-kustomization.j2
    dest: /tmp/{{ cluster_domain }}/platform/flux-system/watches/jenkins.yaml
