---
- name: Create Directory
  file:
    path: /tmp/{{ cluster_fqdn }}/platform/jenkins/default
    state: directory
  tags: [ jenkins ]

- name: Generate and Merge jenkins.gitea.password Variable
  when: jenkins.gitea.password is not defined
  set_fact:
    jenkins: "{{ jenkins | combine({ 'gitea': { 'password': lookup('password', '/dev/null') } } , recursive=true) }}"
  tags: [ jenkins ]

- name: Generate and Merge jenkins.keycloak.password Variable
  when: jenkins.keycloak.password is not defined
  set_fact:
    jenkins: "{{ jenkins | combine({ 'keycloak': { 'password': lookup('password', '/dev/null') } } , recursive=true) }}"
  tags: [ jenkins ]

- name: Template Files
  template:
    src: "{{ item.name }}.j2"
    dest: /tmp/{{ cluster_fqdn }}/platform/jenkins/{{ item.dest | default(item.name) }}.yaml
  when: item.condition | default(true)
  loop:
    - name: configmap-jenkins-config
      dest: default/configmap-jenkins-config
    - name: ingress
      dest: default/ingress
    - name: keycloakclient
      dest: default/keycloakclient
    - name: keycloakuser-jenkins-ci
      dest: default/keycloakuser-jenkins-ci
    - name: secret-gitea-creds
      dest: default/secret-gitea-creds
    - name: secret-keycloak-creds
      dest: default/secret-keycloak-creds
  tags: [ jenkins ]

- name: Template secret-artifacts-registry File
  template:
    src: secret-artifacts-registry.j2
    dest: /tmp/{{ cluster_fqdn }}/platform/jenkins/default/secret-artifacts-registry.yaml
  vars:
    config:
      auths: "{{ { 'registry.' + cluster_fqdn : { 'auth' : ('jenkins-ci:' + jenkins.keycloak.password) | b64encode } } }}"
  tags: [ jenkins ]

- name: Copy Files
  copy:
    src: "{{ item.name }}"
    dest: /tmp/{{ cluster_fqdn }}/platform/jenkins/{{ item.dest | default(item.name) }}
  when: item.condition | default(true)
  loop:
    - name: base-kustomization.yaml
      dest: kustomization.yaml
    - name: instance-kustomization.yaml
      dest: default/kustomization.yaml
    - name: jenkins.yaml
      dest: default/jenkins.yaml
    - name: operator
      dest: ""
  tags: [ jenkins ]

- name: Seal Secrets
  tags: [ requires_cluster, jenkins ]
  when: ('dry-run' not in ansible_run_tags) and (item.condition | default(true))
  shell: |
    kubeseal --format=yaml </tmp/{{ cluster_fqdn }}/platform/jenkins/{{ item.name }}.yaml >/tmp/{{ cluster_fqdn }}/platform/jenkins/{{ item.name }}.tmp
    mv /tmp/{{ cluster_fqdn }}/platform/jenkins/{{ item.name }}.tmp /tmp/{{ cluster_fqdn }}/platform/jenkins/{{ item.name }}.yaml
  loop:
    - name: default/secret-gitea-creds
    - name: default/secret-artifacts-registry
    - name: default/secret-keycloak-creds

- name: Apply Operator Resources
  tags: [ requires_cluster, jenkins ]
  when: ('dry-run' not in ansible_run_tags)
  with_ms3_inc.tavros.kustomize:  /tmp/{{ cluster_fqdn }}/platform/jenkins/operator
  loop_control:
    label: "{{ item.kind }}/{{ item.metadata.name | default('unnamed')}}"
  ms3_inc.tavros.kube:
    kubeconfig: '~/.kube/config'
    definition: "{{ item }}"
    wait: true
    wait_condition: "{{ wait_conditions[item.kind] | default(omit) }}"
    wait_timeout: 900

- name: Apply Resources
  tags: [ requires_cluster, jenkins ]
  when: ('dry-run' not in ansible_run_tags)
  with_ms3_inc.tavros.kustomize:  /tmp/{{ cluster_fqdn }}/platform/jenkins
  loop_control:
    label: "{{ item.kind }}/{{ item.metadata.name | default('unnamed')}}"
  ms3_inc.tavros.kube:
    kubeconfig: '~/.kube/config'
    definition: "{{ item }}"
    wait: true
    wait_condition: "{{ wait_conditions[item.kind] | default(omit) }}"
    wait_timeout: 900

- name: Wait for Jenkins
  tags: [ requires_cluster, jenkins ]
  when: ('dry-run' not in ansible_run_tags)
  ms3_inc.tavros.kube_info:
    kubeconfig: '~/.kube/config'
    kind: Pod
    name: jenkins-tavros
    namespace: jenkins
    wait: true
    wait_timeout: 900
  changed_when: false

- include_tasks: gitea_setup.yaml
  tags: [ jenkins ]

- name: Template flux-kustomization
  template:
    src: flux-kustomization.j2
    dest: /tmp/{{ cluster_fqdn }}/platform/flux-system/watches/jenkins.yaml
  tags: [ jenkins ]
