apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jaeger
resources:
  - ns.yaml
  - https://raw.githubusercontent.com/jaegertracing/jaeger-operator/v1.22.0/deploy/crds/jaegertracing.io_jaegers_crd.yaml
  - https://raw.githubusercontent.com/jaegertracing/jaeger-operator/v1.22.0/deploy/service_account.yaml
  - https://raw.githubusercontent.com/jaegertracing/jaeger-operator/v1.22.0/deploy/role.yaml
  - https://raw.githubusercontent.com/jaegertracing/jaeger-operator/v1.22.0/deploy/role_binding.yaml
  - https://raw.githubusercontent.com/jaegertracing/jaeger-operator/v1.22.0/deploy/operator.yaml
