---
- name: Create directory
  file:
    path: /tmp/{{ cluster_domain }}/platform/kuma-system/meshes/
    state: directory

- name: Process mesh template
  with_list: '{{ meshes }}'
  template:
    src: mesh.j2
    dest: /tmp/{{ cluster_domain }}/platform/kuma-system/meshes/{{ item.mesh_name }}.yaml

- name: Process kuma kustomization template
  template:
    src: kustomization.j2
    dest: /tmp/{{ cluster_domain }}/platform/kuma-system/kustomization.yaml

- name: Copy kuma namespace
  copy:
    src: ns.yaml
    dest: /tmp/{{ cluster_domain }}/platform/kuma-system/ns.yaml

- name: Copy kuma default release
  copy:
    src: default-release.yaml
    dest: /tmp/{{ cluster_domain }}/platform/kuma-system/default-release.yaml

- name: Apply Kuma release
  when: "'dry-run' not in ansible_run_tags"
  shell: |
    kustomize build ./troubadour-base/kuma/ | kubectl apply -f -

- name: Wait for Kuma HelmRelease, and Deployment
  when: "'dry-run' not in ansible_run_tags"
  shell: |
    kubectl -n kuma-system wait --for=condition=ready --timeout=120s helmrelease.helm.toolkit.fluxcd.io --all
    kubectl -n kuma-system wait --for=condition=available --timeout=120s deployments --all

- name: Apply Kuma Mehses
  when: "'dry-run' not in ansible_run_tags"
  shell: |
    kustomize build /tmp/{{ cluster_domain }}/platform/kuma-system/ | kubectl apply -f -

- name: Process flux-kustomization template
  template:
    src: flux-kustomization.j2
    dest: /tmp/{{ cluster_domain }}/platform/flux-system/watches/kuma-system.yaml

# Todo Resolve Restart Issue on Kuma Pod
- name: Wait for Kuma Pod
  when: "'dry-run' not in ansible_run_tags"
  shell: |
    kubectl -n kuma-system wait --for=condition=ready --timeout=120s pods --all
