---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    cluster_name: test
    cluster_domain: troubadour.ms3-inc.com
  tasks:
  - name: Assert binaries are available
    shell: |
      kubectl version
      kustomize version
      flux --version
      kubeseal --version
    changed_when: false

  - name: Install dependencies with pip3 module
    pip:
      name:
        # amazon.aws
        - boto3
        - botocore
        # community.kubernetes
        - openshift
        # community.aws
        - boto
      executable: pip-3
      extra_args: --user

  - import_role:
      name: ms3_inc.troubadour.kubernetes_cluster
    vars:
      cluster_state: present

  - set_fact:
      wait_conditions:
        HelmRelease:
          type: Ready
          status: true
          reason: ReconciliationSucceeded

  - import_role:
      name: ms3_inc.troubadour.fluxtoolkit

  - import_role:
      name: ms3_inc.troubadour.kubeseal

  - import_role:
      name: ms3_inc.troubadour.postgresql

  - include_role:
      name: ms3_inc.troubadour.namespace
    vars:
      namespaces:
      - ns_name: dev
        mesh_name: sandbox
      - ns_name: test
        mesh_name: sandbox
      - ns_name: prod
        mesh_name: prod

  - include_role:
      name: ms3_inc.troubadour.kuma
    vars:
      meshes:
      - mesh_name: prod
        mtls_enabled: true
      - mesh_name: sandbox
        mtls_enabled: true

  - include_role:
      name: ms3_inc.troubadour.keycloak

  - include_role:
      name: ms3_inc.troubadour.kong
    vars:
      kong_name: prod-kong
      mesh_name: prod

  - include_role:
      name: ms3_inc.troubadour.kong
    vars:
      kong_name: sandbox-kong

  - name: Set DNS for keycloak
    when: "'dry-run' not in ansible_run_tags"
    community.aws.route53:
      state: present
      zone: "{{ cluster_domain }}"
      type: CNAME
      record: auth.{{ cluster_name }}.{{ cluster_domain }}
      value: "{{ lookup('k8s', kind='Service', namespace='kong', resource_name='kong-prod-kong-kong-proxy').status.loadBalancer.ingress[0].hostname }}"
      overwrite: true
      wait: yes

  - name: Set wildcard DNS for apps
    when: "'dry-run' not in ansible_run_tags"
    community.aws.route53:
      state: present
      zone: "{{ cluster_domain }}"
      type: CNAME
      record: "*.apps.{{ cluster_name }}.{{ cluster_domain }}"
      value: "{{ lookup('k8s', kind='Service', namespace='kong', resource_name='kong-prod-kong-kong-proxy').status.loadBalancer.ingress[0].hostname }}"
      overwrite: true
      wait: yes


# ## teardown
#   - name: Set DNS for keycloak
#     community.aws.route53:
#       state: absent
#       zone: "{{ cluster_domain }}"
#       type: CNAME
#       record: auth.{{ cluster_name }}.{{ cluster_domain }}
#       value: "{{ lookup('k8s', kind='Service', namespace='kong', resource_name='kong-prod-kong-kong-proxy').status.loadBalancer.ingress[0].hostname }}"
#       overwrite: true
#       wait: yes
#
#   - name: Set wildcard DNS for apps
#     community.aws.route53:
#       state: absent
#       zone: {{ cluster_domain }}
#       type: CNAME
#       record: "*.apps.{{ cluster_name }}.{{ cluster_domain }}"
#       value: "{{ lookup('k8s', kind='Service', namespace='kong', resource_name='kong-prod-kong-kong-proxy').status.loadBalancer.ingress[0].hostname }}"
#       overwrite: true
#       wait: yes
#
#   - import_role:
#       name: ms3_inc.troubadour.kubernetes-cluster
#     vars:
#       cluster_state: absent
