---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Assert binaries are available
    shell: |
      kubectl version
      kustomize version
      flux --version
      kubeseal --version
    changed_when: false

  - name: Install dependencies with pip3 module
    pip:
      name:
        # amazon.aws
        - boto3
        - botocore
        # community.kubernetes
        - openshift
        # community.aws
        - boto
      executable: pip-3
      extra_args: --user

  - import_role:
      name: ms3_inc.troubadour.kubernetes_cluster
    vars:
      cluster_state: present

  - set_fact:
      wait_conditions:
        HelmRelease:
          type: Ready
          status: true
          reason: ReconciliationSucceeded

  - import_role:
      name: ms3_inc.troubadour.fluxtoolkit

  - import_role:
      name: ms3_inc.troubadour.kubeseal

  - import_role:
      name: ms3_inc.troubadour.postgresql

  - include_role:
      name: ms3_inc.troubadour.namespace

  - include_role:
      name: ms3_inc.troubadour.kuma

  - include_role:
      name: ms3_inc.troubadour.cert_manager

  - include_role:
      name: ms3_inc.troubadour.keycloak
    when: keycloak.enabled

  - include_role:
      name: ms3_inc.troubadour.kong

  - name: Set base wildcard DNS
    when: "'dry-run' not in ansible_run_tags"
    community.aws.route53:
      state: present
      zone: "{{ cluster_domain }}"
      type: CNAME
      record: "*.{{ cluster_name }}.{{ cluster_domain }}"
      value: "{{ lookup('k8s', kind='Service', namespace='kong', resource_name='kong-' + kong.default_ingress_controller + '-kong-proxy').status.loadBalancer.ingress[0].hostname }}"
      overwrite: true
      wait: yes

  - name: Set apps wildcard DNS
    when: "'dry-run' not in ansible_run_tags"
    community.aws.route53:
      state: present
      zone: "{{ cluster_domain }}"
      type: CNAME
      record: "*.apps.{{ cluster_name }}.{{ cluster_domain }}"
      value: "{{ lookup('k8s', kind='Service', namespace='kong', resource_name='kong-' + kong.default_ingress_controller + '-kong-proxy').status.loadBalancer.ingress[0].hostname }}"
      overwrite: true
      wait: yes
