---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Assert binaries are available
    shell: |
      kubectl version
      kustomize version
      flux --version
      kubeseal --version
    changed_when: false

  - name: Install dependencies with pip3 module
    pip:
      name:
        - boto3
        - botocore
        - openshift
        - boto
      extra_args: --user

  - import_role:
      name: ms3_inc.troubadour.kubernetes_cluster
    vars:
      cluster_state: present

  - set_fact:
      wait_conditions:
        HelmRelease:
          type: Ready
          status: true
          reason: ReconciliationSucceeded

  - name: Install and configure components
    block:
      - include_role:
          name: ms3_inc.troubadour.fluxtoolkit

      - include_role:
          name: ms3_inc.troubadour.kubeseal

      - include_role:
          name: ms3_inc.troubadour.postgresql

      - include_role:
          name: ms3_inc.troubadour.namespace

      - include_role:
          name: ms3_inc.troubadour.kuma

      - include_role:
          name: ms3_inc.troubadour.cert_manager
        when: cert_manager.enabled

      - include_role:
          name: ms3_inc.troubadour.kong

      - include_role:
          name: ms3_inc.troubadour.keycloak
        when: keycloak.enabled

      - include_role:
          name: ms3_inc.troubadour.kong_ee_keycloak_sso
        when: keycloak.enabled

      - include_role:
          name: ms3_inc.troubadour.nexus
        when: nexus.enabled

      - include_role:
          name: ms3_inc.troubadour.elastic_cloud
        when: elastic_cloud.enabled

    always:
      - copy:
          content: "{{ { 'all': { 'vars': { 'cluster_name': cluster_name, 'cluster_domain': cluster_domain, 'cluster_admin_email': cluster_admin_email, 'kubernetes_cluster': kubernetes_cluster, 'kong': kong, 'kuma': kuma, 'namespaces': namespaces, 'keycloak': keycloak, 'nexus': nexus, 'postgresql': postgresql, 'elastic_cloud': elastic_cloud, 'cert_manager': cert_manager }}} | to_nice_yaml(indent=2) }}"
          dest: /tmp/{{ cluster_domain }}_vars.yaml
