---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - include_tasks: tasks/pre-flight.yaml

  - include_role:
      name: ms3_inc.tavros.kops
    vars:
      cluster_state: present
    tags: [ kops ]

  - name: Install and Configure Components
    block:
      - name: Flux GitOps Toolkit
        include_role:
          name: ms3_inc.tavros.fluxtoolkit
        tags: [ fluxtoolkit ]

      - name: kubeseal
        include_role:
          name: ms3_inc.tavros.kubeseal
        tags: [ kubeseal ]

      - name: PostgreSQL
        include_role:
          name: ms3_inc.tavros.postgresql
        tags: [ postgresql ]

      - name: Namespace
        include_role:
          name: ms3_inc.tavros.namespace
        tags: [ namespace ]

      - name: Kuma
        include_role:
          name: ms3_inc.tavros.kuma
        when: kuma.enabled
        tags: [ kuma ]

      - name: cert-manager
        include_role:
          name: ms3_inc.tavros.cert_manager
        when: cert_manager.enabled
        tags: [ cert_manager ]

      - name: Kong
        include_role:
          name: ms3_inc.tavros.kong
        tags: [ kong ]

      - name: Keycloak
        include_role:
          name: ms3_inc.tavros.keycloak
        when: keycloak.enabled
        tags: [ keycloak ]

      - name: Kong EE SSO
        include_role:
          name: ms3_inc.tavros.kong_ee_sso
        when: keycloak.enabled
        tags: [ kong_ee_sso ]

      - name: Nexus
        include_role:
          name: ms3_inc.tavros.nexus
        when: nexus.enabled
        tags: [ nexus ]

      - name: Elastic Cloud
        include_role:
          name: ms3_inc.tavros.elastic_cloud
        when: elastic_cloud.enabled
        tags: [ elastic_cloud ]

      - name: Jaeger
        include_role:
          name: ms3_inc.tavros.jaeger
        when: jaeger.enabled and keycloak.enabled and not elastic_cloud.ee.enabled
        tags: [ jaeger ]

      - name: Gitea
        include_role:
          name: ms3_inc.tavros.gitea
        when: gitea.enabled
        tags: [ gitea ]

      - name: Jenkins
        include_role:
          name: ms3_inc.tavros.jenkins
        when: jenkins.enabled
        tags: [ jenkins ]

      - name: Flux GitOps Toolkit - Gitea
        include_role:
          name: ms3_inc.tavros.fluxtoolkit_gitea
        when: gitea.enabled
        tags: [ fluxtoolkit_gitea ]

    always:
      - copy:
          content: "{{ { 'all': { 'vars': { 'flux': flux, 'cluster_fqdn': cluster_fqdn, 'cluster_admin_email': cluster_admin_email, 'kubernetes_cluster': kubernetes_cluster, 'kong': kong, 'kuma': kuma, 'namespaces': namespaces, 'keycloak': keycloak, 'nexus': nexus, 'postgresql': postgresql, 'elastic_cloud': elastic_cloud, 'cert_manager': cert_manager, 'gitea': gitea, 'jaeger': jaeger, 'jenkins': jenkins }}} | to_nice_yaml(indent=2) }}"
          dest: /tmp/{{ cluster_fqdn }}_vars.yaml
      - include_role:
          name: ms3_inc.tavros.kops
          tasks_from: tavros_config_backup
        tags: [ requires_cluster]
        when: ('dry-run' not in ansible_run_tags) and kops.enabled
