---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Assert binaries are available
    shell: |
      kubectl version
      kustomize version
      flux --version
      kubeseal --version
    changed_when: false

  - name: Install dependencies with pip3 module
    pip:
      name:
        # amazon.aws
        - boto3
        - botocore
        # community.kubernetes
        - openshift
        # community.aws
        - boto
      executable: pip-3
      extra_args: --user

  - import_role:
      name: ms3_inc.troubadour.kubernetes_cluster
    vars:
      cluster_state: present

  - set_fact:
      wait_conditions:
        HelmRelease:
          type: Ready
          status: true
          reason: ReconciliationSucceeded

  - import_role:
      name: ms3_inc.troubadour.fluxtoolkit

  - import_role:
      name: ms3_inc.troubadour.kubeseal

  - import_role:
      name: ms3_inc.troubadour.postgresql

  - include_role:
      name: ms3_inc.troubadour.namespace

  - include_role:
      name: ms3_inc.troubadour.kuma

  - include_role:
      name: ms3_inc.troubadour.cert_manager
    when: cert_manager.enabled

  - include_role:
      name: ms3_inc.troubadour.kong

  - include_role:
      name: ms3_inc.troubadour.keycloak
    when: keycloak.enabled

  - include_role:
      name: ms3_inc.troubadour.kong_ee_keycloak_sso
    when: keycloak.enabled

  - include_role:
      name: ms3_inc.troubadour.nexus
    when: nexus.enabled

  - copy:
      content: "{{ { 'kubernetes_cluster': kubernetes_cluster, 'kong': kong, 'kuma': kuma, 'namespaces': namespaces, 'keycloak': keycloak, 'nexus': nexus, 'postgresql': postgresql } | to_yaml }}"
      dest: /tmp/{{ cluster_domain }}_vars.yaml
