---
- name: Create Directory
  file:
    path: /tmp/{{ cluster_fqdn }}/platform/cert-manager
    state: directory

- name: Template Files
  template:
    src: "{{ item.name }}.j2"
    dest: /tmp/{{ cluster_fqdn }}/platform/cert-manager/{{ item.dest | default(item.name) }}.yaml
  when: item.condition | default(true)
  loop:
    - name: tavros-clusterissuer

- name: Copy Files
  copy:
    src: "{{ item.name }}"
    dest: /tmp/{{ cluster_fqdn }}/platform/cert-manager/{{ item.dest | default(item.name) }}
  when: item.condition | default(true)
  loop:
    - name: helmrepo.yaml
    - name: kustomization.yaml
    - name: ns.yaml
    - name: release.yaml

- name: Apply Resources
  tags: [ requires_cluster ]
  loop: "{{ lookup('ms3_inc.tavros.kustomize', '/tmp/' + cluster_fqdn + '/platform/cert-manager/', reorder='none') }}"
  community.kubernetes.k8s:
    definition: "{{ item }}"
    wait: true
    wait_condition: "{{ wait_conditions[item.kind] | default(omit) }}"
    wait_timeout: 900
  # adding retry because cert-manager release reports ready before CRDs are stable
  # applying these is an idempotent operation
  # see https://github.com/MS3Inc/tavros/issues/34
  retries: 2
  delay: 3
  register: result
  until: result is succeeded

- name: Template flux-kustomization
  template:
    src: flux-kustomization.j2
    dest: /tmp/{{ cluster_fqdn }}/platform/flux-system/watches/cert-manager.yaml
