name: Tavros Pull Request CI
on:
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  tavros-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.0
      - name: Build tavros-buildtools:latest image
        env:
          IMAGE_TAG: ghcr.io/ms3inc/tavros-buildtools:latest
        run: podman unshare ./.github/workflows/buildtools-build.sh
      - name: Run make install test
        run: podman run -i --rm -v "$PWD:$PWD" -w "$PWD" ghcr.io/ms3inc/tavros-buildtools:latest bash -c "make install test"
