name: Tavros CI
on:
  push:
    branches: [ main ]
jobs:
  buildtools-image:
    runs-on: ubuntu-latest
    container:
      image: quay.io/buildah/stable
      options: --device /dev/fuse --security-opt seccomp=unconfined --security-opt apparmor=unconfined
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          buildtools:
          - 'requirements.txt'
          - '**/buildtools-build.sh'
          - '**/ci.yml'
    - name: Build tavros-buildtools:latest image
      if: steps.filter.outputs.buildtools == 'true'
      env:
        REGISTRY_PSW: ${{ secrets.JAM01_PAT }}
      run: buildah unshare ./.github/workflows/buildtools-build.sh
  test:
    needs: [ buildtools-image ]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ms3inc/tavros-buildtools:latest
    steps:
    - uses: actions/checkout@v2
    - run: make install test
