name: Tavros CI
on:
  push:
    branches: [ main ]
jobs:
  tavros-ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          buildtools:
          - 'requirements.txt'
          - '**/buildtools-build.sh'
          - '**/ci.yml'
    - name: Build tavros-buildtools:latest image
      if: steps.filter.outputs.buildtools == 'true'
      env:
        IMAGE_TAG: ghcr.io/ms3inc/tavros-buildtools:latest
      run: buildah unshare ./.github/workflows/buildtools-build.sh
    - name: Run make install test
      env:
        IMAGE_TAG: ghcr.io/ms3inc/tavros-collection:latest
      run: |
        container=$(buildah from ghcr.io/ms3inc/tavros-buildtools:latest)
        buildah run -v $PWD:$PWD $container -- cd $PWD && make install test && rm -rf /tmp
        buildah config --label name=tavros-collection $container
        buildah commit --rm $container $IMAGE_TAG
    - name: Push tavros-buildtools:latest image
      if: steps.filter.outputs.buildtools == 'true'
      env:
        REGISTRY_PSW: ${{ secrets.JAM01_PAT }}
        IMAGE_TAG: ghcr.io/ms3inc/tavros-buildtools:latest
      run: |
        buildah login --username git --password $REGISTRY_PSW $IMAGE_TAG
        buildah push $IMAGE_TAG
    - name: Push tavros-collection:latest image
      env:
        REGISTRY_PSW: ${{ secrets.JAM01_PAT }}
        IMAGE_TAG: ghcr.io/ms3inc/tavros-collection:latest
      run: |
        buildah login --username git --password $REGISTRY_PSW $IMAGE_TAG
        buildah push $IMAGE_TAG
