name: Tavros CI
on:
  push:
    branches: [ main ]
jobs:
  tavros-ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          buildtools:
          - 'requirements.txt'
          - '**/buildtools-build.sh'
          - '**/ci.yml'
    - name: Build tavros-buildtools:latest image
      if: steps.filter.outputs.buildtools == 'true'
      env:
        IMAGE_TAG: ghcr.io/ms3inc/tavros-buildtools:latest
      run: buildah unshare ./.github/workflows/buildtools-build.sh
    - name: Run make install test
      run: podman run -it --rm -v $PWD:$PWD -w $PWD ghcr.io/ms3inc/tavros-buildtools:latest bash -c "make install test"
    - name: Push tavros-buildtools:latest image
      env:
        REGISTRY_PSW: ${{ secrets.JAM01_PAT }}
        IMAGE: ghcr.io/ms3inc/tavros-buildtools:latest
      run: |
        buildah login --username git --password $REGISTRY_PSW $IMAGE
        buildah push $IMAGE
