name: Tavros Integration Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    container: 
      image: docker.kube.cloudapps.ms3-inc.com/tavros-tools:1.0
      credentials:
        username: gh-bot
        password: ${{ secrets.NEXUS_PASSWORD }}

    steps: 
    - uses: actions/checkout@v1
    - run: make install test
  