name: Tavros Integration Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  test:
    name: Check the repo
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
     
    - name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        registry: docker.kube.cloudapps.ms3-inc.com
        username: gh-bot
        password: ${{ secrets.NEXUS_PASSWORD }}

    - name: Pull and run Docker image 
      run: |
        docker pull docker.kube.cloudapps.ms3-inc.com/tavros-tools:1.0
        docker run -it docker.kube.cloudapps.ms3-inc.com/tavros-tools:1.0
      
    - name: Copy the repo   
      run: cd /root/tavros
    
    - name: Run integration test
      run: make install test
    
 

